#+BLOG: rubikitch
#+POSTID: 212
#+BLOG: rubikitch
#+DATE: [2014-08-14 Thu 11:11]
#+PERMALINK: browse-kill-ring
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: コピー・貼り付け
#+EL_PKG_NAME: browse-kill-ring
#+TAGS: 
#+EL_TITLE0: キルリングを一覧するbrowse-kill-ring.elが更新されました
#+begin: org2blog
#+TITLE: browse-kill-ring.el : キルリングを一覧するbrowse-kill-ring.elが更新されました
[includeme file="inc-package-table.php" name="browse-kill-ring" where="melpa"]
** 概要
Emacsの *kill-ring* (=キルリング=)は複数のテキストを記憶できる、
いわばスーパークリップボードです。

C-yでは直前に記憶した内容を貼り付けますが、
もっと前の内容にするにはM-yを押します。

しかし、かなり前の内容にするには何度もM-yを押す必要があり、
煩わしいものです。

そこでbrowse-kill-ring.elでkill-ringの内容を一覧してしまいましょう。

とはいえ、 *helm* や *anything.el* でも同等の機能が存在するので、
無理してインストールする必要はありません。

M-x *helm-show-kill-ring*
M-x *anything-show-kill-ring*

ここの設定ではM-yをbrowse-kill-ringに置き換えています。
[includeme file="inc-package-install.php" name="browse-kill-ring" where="melpa"]

#+end:
** 概要                                                             :noexport:
Emacsの *kill-ring* (=キルリング=)は複数のテキストを記憶できる、
いわばスーパークリップボードです。

C-yでは直前に記憶した内容を貼り付けますが、
もっと前の内容にするにはM-yを押します。

しかし、かなり前の内容にするには何度もM-yを押す必要があり、
煩わしいものです。

そこでbrowse-kill-ring.elでkill-ringの内容を一覧してしまいましょう。

とはいえ、 *helm* や *anything.el* でも同等の機能が存在するので、
無理してインストールする必要はありません。

M-x *helm-show-kill-ring*
M-x *anything-show-kill-ring*

ここの設定ではM-yをbrowse-kill-ringに置き換えています。
** 設定 [[http://rubikitch.com/f/140814110949.browse-kill-ring.el][140814110949.browse-kill-ring.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/140814/140814110949.browse-kill-ring.el"
#+BEGIN_SRC fundamental
(global-set-key (kbd "M-y") 'browse-kill-ring)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140814110949.browse-kill-ring.el
$ emacs -Q -f package-initialize -l 140814110949.browse-kill-ring.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140814111944.png
Fig1: キルリングの内容を一覧！


** 使い方
browse-kill-ringを起動したら、pとnで前後の内容を選択し、RETで貼り付けます。

*Kill Ring*バッファは普通のバッファなので
isearchして選択したい内容に素早く到達できます。

また、lで絞り込み検索したり、eで内容を変更したりもできます。
[includeme file="inc-package-relate.php" name="browse-kill-ring"]
