#+BLOG: rubikitch
#+POSTID: 203
#+DATE: [2014-08-25 Mon 12:13]
#+PERMALINK: neotree
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs
#+EL_PKG_NAME: neotree
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, dired-subtree, dired-toggle, NerdTree emacs, relate:dired, relate:speedbar
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: VimのNerdTreeをEmacsで！diredやspeedbarみたいなやつ
#+EL_URL: http://www.emacswiki.org/emacs/NeoTree
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージneotreeの紹介
#+MYTAGS: package:neotree, emacs 使い方, emacs コマンド, emacs, emacs lisp neotree, elisp neotree, emacs melpa neotree, emacs neotree 使い方, emacs neotree 設定, emacs パッケージ neotree, emacs neotree スクリーンショット, dired-subtree, dired-toggle, NerdTree emacs, relate:dired, relate:speedbar
#+TITLE: emacs neotree.el : VimのNerdTreeをEmacsで！diredやspeedbarみたいなやつ | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>neotree</td></tr>
<tr><td>概要(原文)</td><td>A tree plugin like NerdTree for Vim</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>サイト</td><td><a href="http://www.emacswiki.org/emacs/NeoTree">http://www.emacswiki.org/emacs/NeoTree</td></tr>
<tr><td>取得先</td><td><a href="https://github.com/jaypei/emacs-neotree">https://github.com/jaypei/emacs-neotree</a></td></tr>
<tr><td>バージョン</td><td>20141119.443</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:neotree/">package:neotree</a> <a href="http://rubikitch.com/tag/package:dired/">package:dired</a> <a href="http://rubikitch.com/tag/package:speedbar/">package:speedbar</a></td></tr>
</table>
<br />
#+END_HTML
neotreeはVimの *NerdTree* をEmacsに移植したものです。

M-x neotreeを実行すると、左側にファイルリストがポップアップしてきます。

そして、RETを押すと、ファイルやディレクトリを開きます。

ファイルに対してRETを押すと右側のウィンドウでファイルを開き、
ディレクトリに対してRETを押すと、NeoTree上にディレクトリが展開されます。

qを押せばNeoTreeのウィンドウが消えます。

NeoTreeは *dedicated window* なので、NeoTreeのウィンドウで
バッファやファイルを開こうとすると必ず右側で開かれます。

dedicated windowというのは、そのバッファ専用のウィンドウであり、
他のバッファにウィンドウをゆずらないからです。
** neotree インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install neotree


#+end:
** 概要                                                             :noexport:
neotreeはVimの *NerdTree* をEmacsに移植したものです。

M-x neotreeを実行すると、左側にファイルリストがポップアップしてきます。

そして、RETを押すと、ファイルやディレクトリを開きます。

ファイルに対してRETを押すと右側のウィンドウでファイルを開き、
ディレクトリに対してRETを押すと、NeoTree上にディレクトリが展開されます。

qを押せばNeoTreeのウィンドウが消えます。

NeoTreeは *dedicated window* なので、NeoTreeのウィンドウで
バッファやファイルを開こうとすると必ず右側で開かれます。

dedicated windowというのは、そのバッファ専用のウィンドウであり、
他のバッファにウィンドウをゆずらないからです。

** 総評
まだできたてホヤホヤなのであまり大したことができるわけではありません。

現時点では *dired* で十分なのではないでしょうか。

サブディレクトリをバッファに展開するのであれば標準のdiredでも
「i」でできてしまいますし、NeoTreeと同じような見た目にしたければ
*dired-subtree* パッケージを使えばできます。

左側にファイルリストを配置するのも *dired-toggle* をインストールして、
M-x dired-toggleでできてしまいます。
# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140825121535.png
Fig1: M-x neotree
