#+BLOG: rubikitch
#+POSTID: 255
#+BLOG: rubikitch
#+DATE: [2014-08-30 Sat 07:18]
#+PERMALINK: helm-descbinds
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:キーバインドを絞り込み検索して実行したり説明を見たり
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: キーバインド
#+EL_PKG_NAME: helm-descbinds
#+TAGS: helm, るびきちオススメ, 初心者安心
#+EL_TITLE0: キーバインドを絞り込み検索！helmを使えばもう迷わない
#+begin: org2blog
#+TITLE: helm-descbinds.el : キーバインドを絞り込み検索！helmを使えばもう迷わない
[includeme file="inc-package-table.php" name="helm-descbinds" where="melpa"]
** 概要
キーバインドを調べるとき
<f1> bかプレフィクスキーの後にC-hを押しますよね。

でも、キー一覧の*Help*バッファを見るには
わざわざC-x oでウィンドウを切り替えてスクロールするか
延々とC-M-vをしていく必要があり、面倒です。

そこで、<f1> bに絞り込み検索機能をつけたのがhelm-descbinds.elです。

その名のとおり、helmのインターフェースでキーを検索してくれます。

helmは *anything.el* の後継の絞り込み検索フレームワークです。

絞り込み検索した後RETを押せばそのコマンドが実行できます。

RETの代わりに<f2>で *describe-key* (コマンドの説明)、
<f3>で *find-function-on-key* (コマンドの定義にジャンプ)
の機能も呼べます。




とにかくこれは入れておきましょう。

*guide-key.el* と併用すればもうキーバインドで迷子になることはありません。
[includeme file="inc-package-install.php" name="helm-descbinds" where="melpa"]

#+end:
** 概要                                                             :noexport:
キーバインドを調べるとき
<f1> bかプレフィクスキーの後にC-hを押しますよね。

でも、キー一覧の*Help*バッファを見るには
わざわざC-x oでウィンドウを切り替えてスクロールするか
延々とC-M-vをしていく必要があり、面倒です。

そこで、<f1> bに絞り込み検索機能をつけたのがhelm-descbinds.elです。

その名のとおり、helmのインターフェースでキーを検索してくれます。

helmは *anything.el* の後継の絞り込み検索フレームワークです。

絞り込み検索した後RETを押せばそのコマンドが実行できます。

RETの代わりに<f2>で *describe-key* (コマンドの説明)、
<f3>で *find-function-on-key* (コマンドの定義にジャンプ)
の機能も呼べます。




とにかくこれは入れておきましょう。

*guide-key.el* と併用すればもうキーバインドで迷子になることはありません。
** 設定 [[http://rubikitch.com/f/140830072000.helm-descbinds.el][140830072000.helm-descbinds.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/140830/140830072000.helm-descbinds.el"
#+BEGIN_SRC fundamental
(helm-descbinds-install)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140830072000.helm-descbinds.el
$ emacs -Q -f package-initialize -l 140830072000.helm-descbinds.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140830072114.png
Fig1: C-x C-h

http://rubikitch.com/f/20140830072122.png
Fig2: アクション
[includeme file="inc-package-relate.php" name="helm-descbinds"]
