#+BLOG: rubikitch
#+POSTID: 221
#+DATE: [2014-08-27 Wed 17:35]
#+PERMALINK: yaml-mode
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs
#+EL_PKG_NAME: yaml-mode
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, emacs YAML
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: EmacsでYAMLを編集するyaml-modeが進化していた
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージyaml-modeの紹介
#+MYTAGS: package:yaml-mode, emacs 使い方, emacs コマンド, emacs, emacs lisp yaml-mode, elisp yaml-mode, emacs melpa yaml-mode, emacs yaml-mode 使い方, emacs yaml-mode 設定, emacs パッケージ yaml-mode, emacs yaml-mode スクリーンショット, emacs YAML
#+TITLE: emacs yaml-mode.el : EmacsでYAMLを編集するyaml-modeが進化していた | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>yaml-mode</td></tr>
<tr><td>概要(原文)</td><td>Major mode for editing YAML files</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/yoshiki/yaml-mode">https://github.com/yoshiki/yaml-mode</a></td></tr>
<tr><td>バージョン</td><td>20141125.37</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:yaml-mode/">package:yaml-mode</a> </td></tr>
</table>
<br />
#+END_HTML
EmacsでYAMLを編集するyaml-modeが更新されていました。

以前よりもインデントや色付け(font-lock)が賢くなっているようです。

YAMLは今更説明する必要はないと思いますが、
オブジェクトをファイルに保存するフォーマットのひとつで、
読み書きしやすいテキストファイルであることが特徴です。

あらゆる場面で使われているYAMLですが、
そのメジャーモードがEmacs標準になっていないのが不思議です。
** yaml-mode インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install yaml-mode


#+end:
** 概要                                                             :noexport:
EmacsでYAMLを編集するyaml-modeが更新されていました。

以前よりもインデントや色付け(font-lock)が賢くなっているようです。

YAMLは今更説明する必要はないと思いますが、
オブジェクトをファイルに保存するフォーマットのひとつで、
読み書きしやすいテキストファイルであることが特徴です。

あらゆる場面で使われているYAMLですが、
そのメジャーモードがEmacs標準になっていないのが不思議です。

** 設定 [[http://rubikitch.com/f/140827172956.yaml-mode.1.el][140827172956.yaml-mode.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/140827/140827172956.yaml-mode.1.el"
#+BEGIN_SRC fundamental
(require 'yaml-mode)
(add-to-list 'auto-mode-alist '("\\.ya?ml$" . yaml-mode))
(define-key yaml-mode-map "\C-m" 'newline-and-indent)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140827172956.yaml-mode.1.el
$ emacs -Q -f package-initialize -l 140827172956.yaml-mode.1.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140827173534.png
Fig1: yaml-mode
