#+BLOG: rubikitch
#+POSTID: 200
#+BLOG: rubikitch
#+DATE: [2014-08-12 Tue 08:21]
#+PERMALINK: chruby
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Ruby支援
#+EL_PKG_NAME: chruby
#+TAGS: 外部プログラム使用, use:ruby
#+EL_TITLE0: chruby/chruby.el:Rubyのバージョンを切り替える最新の方法
#+begin: org2blog
#+TITLE: chruby.el : chruby/chruby.el:Rubyのバージョンを切り替える最新の方法
[includeme file="inc-package-table.php" name="chruby" where="melpa"]
** 概要
chrubyはRubyのバージョンを切り替えるものです。

類似のものにrbenvやrvmがありますが、
chrubyの方が新しく、シンプルな仕組みになっています。

RSpecなどのgemによってインストールされたコマンドを
そのまま実行できるメリットもあります。

rbenvだとrbenv rehashが必要になります。

chrubyは[[https://github.com/postmodern/chruby/][シェル版]] とelisp版があります。

chruby.elをインストールすると、
Emacs内部で使うRuby(eshellやcall-process)でも
Rubyの切り替えができるようになります。

chrubyを使う前にruby-installで使うRubyをインストールしてください。

http://www.oiax.jp/rails/zakkan/chruby_on_ubuntu.html
がとても詳しいです。

パッケージでインストールすれば設定は不要です。
[includeme file="inc-package-install.php" name="chruby" where="melpa"]

#+end:
** 概要                                                             :noexport:
chrubyはRubyのバージョンを切り替えるものです。

類似のものにrbenvやrvmがありますが、
chrubyの方が新しく、シンプルな仕組みになっています。

RSpecなどのgemによってインストールされたコマンドを
そのまま実行できるメリットもあります。

rbenvだとrbenv rehashが必要になります。

chrubyは[[https://github.com/postmodern/chruby/][シェル版]] とelisp版があります。

chruby.elをインストールすると、
Emacs内部で使うRuby(eshellやcall-process)でも
Rubyの切り替えができるようになります。

chrubyを使う前にruby-installで使うRubyをインストールしてください。

http://www.oiax.jp/rails/zakkan/chruby_on_ubuntu.html
がとても詳しいです。

パッケージでインストールすれば設定は不要です。
** 使い方
*** eshell
#+BEGIN_EXAMPLE
eshell $ chruby "1.9"; ruby -v
("/r/.gem/ruby/2.1.0/bin" "/r/.rubies/ruby-1.9.3-p547/bin")
ruby 1.9.3p547 (2014-05-14) [x86_64-linux]
eshell $ chruby "2"; ruby -v
("/r/.gem/ruby/2.1.0/bin" "/r/.rubies/ruby-2.1.2/bin")
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
#+END_EXAMPLE
*** call-process
#+begin_src emacs-lisp
(defun chruby-test (ver)
  (with-temp-buffer
    (chruby ver)
    (call-process "ruby" nil t nil "-v")
    (buffer-string)))
(chruby-test "1.9") ; => "ruby 1.9.3p547 (2014-05-14) [x86_64-linux]\n"
(chruby-test "2")   ; => "ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]\n"
#+end_src
[includeme file="inc-package-relate.php" name="chruby"]
