#+BLOG: rubikitch
#+POSTID: 23
#+BLOG: rubikitch
#+DATE: [2014-08-13 Wed 23:22]
#+PERMALINK: 151
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: メルマガ『Emacsの鬼るびきちのココだけの話』の読者数が150人を超え、読者さんからありがたいメールを頂きました。
#+TAGS: 
#+TITLE: メルマガ読者数が150人を超えました！嬉しいメールも　『Emacsの鬼るびきちのココだけの話』
ども、るびきちです。

久しぶりにメルマガの読者数を見たところ、
/なんと151人になっていました！/

ついに初代ポケモンの数に並びました。

[[http://www.amazon.co.jp/dp/4774148970/][『Emacs Lispテクニックバイブル　〜真髄を知るLispの掟〜』]]
刊行と同時に始めた有料メルマガ[[http://www.mag2.com/m/0001373131.html][『Emacsの鬼るびきちのココだけの話』]] ですが、
始めた当初から140人前後の読者さんに恵まれていました。

この状態で2年半ずっと一定の読者数でしたが、
念願の150人を超えることができました。

解除せずにここまでついてきてくれた読者さんすべてに心から感謝いたします。

/ありがとうございます。/

これからも毎週精一杯のコンテンツをお届けするので
応援よろしくお願いします。
** 読者さんから嬉しいメールが
さらに嬉しいことに、読者のH.Oさんからこのようなメールを頂きました。

7月から今月にかけて僕が開発した [[http://rubikitch.com/tag/org%25e7%25bf%2592%25e6%2585%25a3%25e4%25bb%2595%25e4%25ba%258b%25e8%25a1%2593/][org習慣仕事術]] という仕事術を取り上げました。

これは日々のタスクを *習慣* に落とし込んで
確実に物事を前に進める *脳科学に基いた手法* を、
[[http://rubikitch.com/tag/org-mode/][org-mode]] で実装したものです。

どうも日々の仕事がうまく進まない、
*ダイエット* や *筋トレ* が続かない、
新しい *プログラミング言語* が覚えられない…

などの悩みがあるEmacsユーザは
[[http://www.mag2.com/m/0001373131.html][メルマガ講読]] をした上で、
[[http://www.mag2.com/archives/0001373131/][7月号のバックナンバー講読]] してください。

日々のTODO管理とも両立できる手法です。
*** 1通目
#+BEGIN_QUOTE
org習慣仕事術を読んで、久しぶりにメールします。

emacsは相変わらず、テキスト編集やw3mくらいでしか使わないのですが、一連のorg習慣仕事術は、感銘を受けました。

emacsだけでできるというのは、ある意味素晴らしいことなのですが、最近、インターネット、クラウド環境が発達し、しかも情報をmobile機器を含み取り出すということで、emacsではちょっとということが多くなりました(例えば、scheduleはgoogle
calender、mailはgmail、メモはevernote）。しかし、今回の一連の記事、emacsでやらなくとも、その習慣仕事術のエッセンスは他に応用が利きます。

私は、早速ATOKでお気に入り文書でテンプレート挿入し、ATOK
Pad(Evernoteに同期するメモ)で進捗管理するようになりました。これは、非常に有用で、少しずつコンピュータを使ってする勉強は、苦にならなくなってきました。また、協力なEvernoteの検索やlist化で後で成果を並べるのも楽しいので、習慣化のモチベーションにもなります。

emacsで新しいことをしても最近定着しないことが殆どなのですが、このようなフレームワーク(習慣仕事術)的なことを紹介していただけると、非常に有用です。emacsのメルマガですが、emacsを抜けだし進化したように感じました。

以上、感想まで。  それでは、今後もメルマガ楽しみにしています。
#+END_QUOTE

*** 2通目
#+BEGIN_QUOTE
今回のようにフレームワークを示して、その一例を
Emacsでやるとスタイルは非常にうれしいです。製品を作るときといっしょで、まずEmacs
の機能ありきではなくて、ユーザーのユースケース(仕事のフレームワーク)を提案して
いただき、それをEmacsの機能で実装するというのは、非常に興味深いです。

あと、前に書き忘れましたが、習慣化で仕事をすると効率的に仕事をしょうかできることを
実感しました。。

やるべきことをlist化して消化していくTodo listでは、どうしてもPriorityだけで時間に終われない
ので、なかなかTodo listを消化できないのですが、習慣化では、時間を決めてルーチン化し、
それを消化していくので、非常に時間管理がやりやすくなります。ルーチンを消化しなくては
ならない(したくなる)ので、途中で現実逃避することも少なくなります。

Todoもscheduleに落として行けば時間管理できるのですが、習慣化した時間と、schedule
した時間では、始める時の心理的障壁が全然違います。
#+END_QUOTE
