#+BLOG: rubikitch
#+POSTID: 170
#+DATE: [2014-08-15 Fri 08:25]
#+PERMALINK: pretty-symbols
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs
#+EL_PKG_NAME: pretty-symbols
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, emacs lambda λ 表示, emacs pretty-mode, emacs pretty-symbols-mode, emacs font-lock,
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: pretty-symbols.elでlambdaをλと表示してみよう。その他のキーワードにも対応！
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージpretty-symbolsの紹介
#+MYTAGS: package:pretty-symbols, emacs 使い方, emacs コマンド, emacs, emacs lisp pretty-symbols, elisp pretty-symbols, emacs melpa pretty-symbols, emacs pretty-symbols 使い方, emacs pretty-symbols 設定, emacs パッケージ pretty-symbols, emacs pretty-symbols スクリーンショット, emacs lambda λ 表示, emacs pretty-mode, emacs pretty-symbols-mode, emacs font-lock,
#+TITLE: emacs pretty-symbols.el : pretty-symbols.elでlambdaをλと表示してみよう。その他のキーワードにも対応！ | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>pretty-symbols</td></tr>
<tr><td>概要(原文)</td><td>Draw tokens as Unicode glyphs.</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/drothlis/pretty-symbols">https://github.com/drothlis/pretty-symbols</a></td></tr>
<tr><td>バージョン</td><td>20140814.259</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:pretty-symbols/">package:pretty-symbols</a> </td></tr>
</table>
<br />
#+END_HTML
pretty-symbols.elは *lambda* や *nil* などのプログラミング言語のキーワードに
対して対応する文字を表示するものです。

ここで載せる設定は現時点で対応しているメジャーモードすべてに設定しています。

デフォルトは lambda→λ の置換のみですが、
*pretty-symbol-categories* を設定するとあらゆるキーワードに対応します。
** pretty-symbols インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install pretty-symbols


#+end:
** 概要                                                             :noexport:
pretty-symbols.elは *lambda* や *nil* などのプログラミング言語のキーワードに
対して対応する文字を表示するものです。

ここで載せる設定は現時点で対応しているメジャーモードすべてに設定しています。

デフォルトは lambda→λ の置換のみですが、
*pretty-symbol-categories* を設定するとあらゆるキーワードに対応します。
** 設定 [[http://rubikitch.com/f/140815073241.pretty-symbols.1.el][140815073241.pretty-symbols.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/140815/140815073241.pretty-symbols.1.el"
#+BEGIN_SRC fundamental
;; デフォルトはlambdaのみだが、すべて有効にしてしまうと…
(setq pretty-symbol-categories '(lambda logical relational nil))
;; 対応メジャーモードのフックを設定する
(add-hook 'emacs-lisp-mode-hook 'pretty-symbols-mode)
(add-hook 'inferior-lisp-mode-hook 'pretty-symbols-mode)
(add-hook 'inferior-emacs-lisp-mode-hook 'pretty-symbols-mode)
(add-hook 'c-mode-hook 'pretty-symbols-mode)
(add-hook 'c++-mode-hook 'pretty-symbols-mode)
(add-hook 'go-mode-hook 'pretty-symbols-mode)
(add-hook 'java-mode-hook 'pretty-symbols-mode)
(add-hook 'js-mode-hook 'pretty-symbols-mode)
(add-hook 'perl-mode-hook 'pretty-symbols-mode)
(add-hook 'cperl-mode-hook 'pretty-symbols-mode)
(add-hook 'ruby-mode-hook 'pretty-symbols-mode)
(add-hook 'python-mode-hook 'pretty-symbols-mode)
(add-hook 'inferior-python-mode-hook 'pretty-symbols-mode)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140815073241.pretty-symbols.1.el
$ emacs -Q -f package-initialize -l 140815073241.pretty-symbols.1.el
#+END_EXAMPLE
# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140815083047.png
Fig1: ビフォー

http://rubikitch.com/f/20140815083054.png
Fig2: アフター
