#+BLOG: rubikitch
#+POSTID: 237
#+BLOG: rubikitch
#+DATE: [2014-08-25 Mon 12:13]
#+PERMALINK: neotree
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:VimのNerdTreeっぽいファイラ
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ファイラ
#+EL_PKG_NAME: neotree
#+TAGS: from:vim
#+EL_TITLE0: VimのNerdTreeをEmacsで！diredやspeedbarみたいなやつ
#+EL_URL: http://www.emacswiki.org/emacs/NeoTree
#+begin: org2blog
#+TITLE: neotree.el : VimのNerdTreeをEmacsで！diredやspeedbarみたいなやつ
[includeme file="inc-package-table.php" name="neotree" where="melpa"]
** 概要
neotreeはVimの *NerdTree* をEmacsに移植したものです。

M-x neotreeを実行すると、左側にファイルリストがポップアップしてきます。

そして、RETを押すと、ファイルやディレクトリを開きます。

ファイルに対してRETを押すと右側のウィンドウでファイルを開き、
ディレクトリに対してRETを押すと、NeoTree上にディレクトリが展開されます。

qを押せばNeoTreeのウィンドウが消えます。

NeoTreeは *dedicated window* なので、NeoTreeのウィンドウで
バッファやファイルを開こうとすると必ず右側で開かれます。

dedicated windowというのは、そのバッファ専用のウィンドウであり、
他のバッファにウィンドウをゆずらないからです。
[includeme file="inc-package-install.php" name="neotree" where="melpa"]

#+end:
** 概要                                                             :noexport:
neotreeはVimの *NerdTree* をEmacsに移植したものです。

M-x neotreeを実行すると、左側にファイルリストがポップアップしてきます。

そして、RETを押すと、ファイルやディレクトリを開きます。

ファイルに対してRETを押すと右側のウィンドウでファイルを開き、
ディレクトリに対してRETを押すと、NeoTree上にディレクトリが展開されます。

qを押せばNeoTreeのウィンドウが消えます。

NeoTreeは *dedicated window* なので、NeoTreeのウィンドウで
バッファやファイルを開こうとすると必ず右側で開かれます。

dedicated windowというのは、そのバッファ専用のウィンドウであり、
他のバッファにウィンドウをゆずらないからです。

** 総評
まだできたてホヤホヤなのであまり大したことができるわけではありません。

現時点では *dired* で十分なのではないでしょうか。

サブディレクトリをバッファに展開するのであれば標準のdiredでも
「i」でできてしまいますし、NeoTreeと同じような見た目にしたければ
*dired-subtree* パッケージを使えばできます。

左側にファイルリストを配置するのも *dired-toggle* をインストールして、
M-x dired-toggleでできてしまいます。
# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140825121535.png
Fig1: M-x neotree
[includeme file="inc-package-relate.php" name="neotree"]
