#+BLOG: rubikitch
#+POSTID: 273
#+BLOG: rubikitch
#+DATE: [2014-09-06 Sat 04:46]
#+PERMALINK: linked-buffer
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:同じ内容をキープし続ける2つのバッファを使って1つのバッファで複数のメジャーモードを実現させる
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: 複数のメジャーモード
#+EL_PKG_NAME: lentic
#+TAGS: org
#+EL_TITLE0: 【linked-bufferから改名】1つのファイルで複数のメジャーモードを使う直観的な方法！org-babelが便利に
#+begin: org2blog
#+TITLE: lentic.el : 【linked-bufferから改名】1つのファイルで複数のメジャーモードを使う直観的な方法！org-babelが便利に
[includeme file="inc-package-table.php" name="lentic" where="melpa"]

#+end:
** 概要
<2014-12-16 Tue>linked-bufferからlenticに改名されました。

今回はすごいマイナーなパッケージを紹介します。

というか知られてなさすぎて日本語のブログでは取り上げられてないです。

lentic.elは *indirect-buffer* のように
同じ内容をキープし続ける2つのバッファを使って
1つのバッファで複数のメジャーモードを実現させます。

2つのバッファを同時に表示して、カーソル位置も連動してくれるので、
単にウィンドウを切り替えるだけでメジャーモードを使い分けられます。

*org-mode* で文書中にソースコードを書くときに使うと便利です。

逆に、複数のファイルを1つのバッファに統合するには [[http://emacs.rubikitch.com/multifiles/][multifiles.el]] を使います。
[includeme file="inc-package-install.php" name="lentic" where="melpa"]
** 設定 [[http://rubikitch.com/f/140906050929.linked-buffer.1.el][140906050929.linked-buffer.1.el(以下のコードと同一)]]
autoloadの設定がされていないので、requireの必要があります。

#+BEGIN: include :file "/r/sync/junk/140906/140906050929.linked-buffer.1.el"
#+BEGIN_SRC fundamental
(require 'lentic)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140906050929.linked-buffer.1.el
$ emacs -Q -f package-initialize -l 140906050929.linked-buffer.1.el
#+END_EXAMPLE

** 使い方
たとえば、こんなorg文書があるとします。

#+BEGIN_EXAMPLE
==== ここから
org-babelでorg文書にソースコード書けるよねー。

#+begin_src emacs-lisp
(setq hoge 100)
#+end_src

けれど、毎回 C-c ' するの面倒！

#+BEGIN_SRC emacs-lisp
(defun hoge ()
  (+ (length "abc") 999))
#+END_SRC

そこでlenticを使いましょう。
==== ここまで
#+END_EXAMPLE


この状態で *M-x lentic-split-window-right* を実行すると、
右側に同じ内容のバッファが登場します。

そして、一方のカーソルを動かすと、他方のカーソルも移動し、
一方を編集すると、他方も編集されます。

ここで右側のバッファを *emacs-lisp-mode* にしておけば、
ソースブロックをそのまま編集できます。

ただし、保存は元のバッファで行ってください。

なお、上下分割バージョンは *M-x lentic-split-window-below* です。

まだ開発が始まったばかりなので、今後に期待です。
# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140906051044.png
Fig1: 左右のバッファを連動させて編集！！
[includeme file="inc-package-relate.php" name="lentic"]
