#+BLOG: rubikitch
#+POSTID: 277
#+BLOG: rubikitch
#+DATE: [2014-09-07 Sun 14:14]
#+PERMALINK: tabbar
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:header-lineにバッファリストを表示させて切替えられるようにする
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: バッファ切り替え
#+EL_PKG_NAME: tabbar
#+TAGS: 初心者安心, header-line
#+EL_TITLE0: Emacsをタブエディタ化し、バッファを俯瞰する
#+begin: org2blog
#+TITLE: tabbar.el : Emacsをタブエディタ化し、バッファを俯瞰する
[includeme file="inc-package-table.php" name="tabbar" where="melpa"]
** 概要
[[http://emacs.rubikitch.com/elscreen/][この前elscreenを紹介したばかりだが、]]
対抗馬といわれているtabbar.elも見てみましょう。

始めに言っておきますが、 *elscreen.el* とは別物です。

tabbar.elではバッファ一覧を表示するのに対し、
elscreen.elではウィンドウ構成一覧を表示します。

これはバッファリストを *header-line* に並べて
順次切り替えられるようにするものです。
[includeme file="inc-package-install.php" name="tabbar" where="melpa"]

#+end:
** 概要                                                             :noexport:
[[http://emacs.rubikitch.com/elscreen/][この前elscreenを紹介したばかりだが、]]
対抗馬といわれているtabbar.elも見てみましょう。

始めに言っておきますが、 *elscreen.el* とは別物です。

tabbar.elではバッファ一覧を表示するのに対し、
elscreen.elではウィンドウ構成一覧を表示します。

これはバッファリストを *header-line* に並べて
順次切り替えられるようにするものです。

** 設定 [[http://rubikitch.com/f/140907152621.tabbar.el][140907152621.tabbar.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/140907/140907152621.tabbar.el"
#+BEGIN_SRC fundamental
(tabbar-mode 1)
;; タブ上でマウスホイール操作無効
(tabbar-mwheel-mode -1)
;; グループ化しない
(setq tabbar-buffer-groups-function nil)
;; 画像を使わないことで軽量化する
(setq tabbar-use-images nil)
;; キーに割り当てる
(global-set-key (kbd "M-<right>") 'tabbar-forward-tab)
(global-set-key (kbd "M-<left>") 'tabbar-backward-tab)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140907152621.tabbar.el
$ emacs -Q -f package-initialize -l 140907152621.tabbar.el
#+END_EXAMPLE

tabbarシンプルに使うのならば、グループは使わなくてよいです。

この設定ではM-←とM-→でタブ(バッファ)を切り替えられます。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20140907165736.png
Fig1: タブをheader-lineに表示する！
** APELはもう使われていない
軽くぐぐったところ、
APELに依存しているから乗り換えた
という記事をちょくちょく見掛けます。

現在MELPAで入手できるelscreen.elでは、
とっくのとうにAPELとの依存関係は断ち切っています。

https://github.com/shosti/elscreen/commit/9dab9fb8b594e120982b39663c66699f6d057971

#+BEGIN_EXAMPLE
9dab9fb8b594e120982b39663c66699f6d057971
Author: Emanuel Evans <emanuel.evans@gmail.com>
Date:   Wed Apr 11 14:44:03 2012 -0400

    Remove dependency on alist

    Get rid of APEL

#+END_EXAMPLE

情報というのは刻一刻と変化します。

その記事はいつ書かれたものかを見ましょう。


** 総評
バッファリストを常に表示して俯瞰できるようにしたい方は
導入しても損はありません。

ただ、たくさんのバッファを開いていると、
当然header-lineはうるさくなります。

おまけに、C-x 3で左右分割すると表示できる領域が
すぐに狹くなってしまいます。

バッファを俯瞰して切り替える方法ならば、
[[http://emacs.rubikitch.com/ace-jump-buffer/][ace-jump-buffer.el]] や *helm* を使うこともできます。

そう考えると僕的にはタブエディタ化は[[http://emacs.rubikitch.com/elscreen/][elscreen]] の方をおすすめします。
[includeme file="inc-package-relate.php" name="tabbar"]
