#+BLOG: rubikitch
#+POSTID: 318
#+BLOG: rubikitch
#+DATE: [2014-09-28 Sun 12:39]
#+PERMALINK: id-manager
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t
#+ISPAGE: nil
#+DESCRIPTION:ローカルに暗号化ファイルにパスワードをまとめて保存することでパスワードを管理。helmインターフェース付き。
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: パスワード管理
#+EL_PKG_NAME: id-manager
#+TAGS: helm, るびきちオススメ
#+EL_TITLE0: Emacs/helmでパスワード一元管理！Emacs Lispからパスワードにアクセスする方法
#+EL_DOC: id-password management
#+EL_URL: https://github.com/kiwanami/emacs-id-manager/
#+begin: org2blog
#+TITLE: id-manager.el : Emacs/helmでパスワード一元管理！Emacs Lispからパスワードにアクセスする方法
[includeme file="inc-package-table.php" name="id-manager" where="melpa"]
** 概要
*id-manager.el* は、Emacsで各サービスのパスワードを管理するものです。

同じ目的のツールとしてブラウザの拡張に *LastPass* などがありますが、
クラウドに全パスワードを保存するということは、
パスワードを預けたサーバがクラックされると
全てのパスワードがダダ漏れになってしまうリスクがあります。

そこでローカルファイルにパスワードを暗号化して保存しておく方法もあります。

また、Emacs LispからID・パスワードにアクセスできるので、
パスワードを平文で設定する必要がなくなり、
*セキュリティ* が保たれます。


詳しくは開発者の記事を見てください。

http://d.hatena.ne.jp/kiwanami/20110221/1298293727

なお、最新版では *anything.el* ではなくて *helm.el* との連携になっています。

helmとともに楽々パスワード管理を楽しんでください。
[includeme file="inc-package-install.php" name="id-manager" where="melpa"]

#+end:
[[http://emacs.rubikitch.com/quelpa/][quelpa]] は一度入れておくと楽チンです。
** 概要                                                             :noexport:
*id-manager.el* は、Emacsで各サービスのパスワードを管理するものです。

同じ目的のツールとしてブラウザの拡張に *LastPass* などがありますが、
クラウドに全パスワードを保存するということは、
パスワードを預けたサーバがクラックされると
全てのパスワードがダダ漏れになってしまうリスクがあります。

そこでローカルファイルにパスワードを暗号化して保存しておく方法もあります。

また、Emacs LispからID・パスワードにアクセスできるので、
パスワードを平文で設定する必要がなくなり、
*セキュリティ* が保たれます。


詳しくは開発者の記事を見てください。

http://d.hatena.ne.jp/kiwanami/20110221/1298293727

なお、最新版では *anything.el* ではなくて *helm.el* との連携になっています。

helmとともに楽々パスワード管理を楽しんでください。

** 設定 [[http://rubikitch.com/f/140928130442.id-manager.el][140928130442.id-manager.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/140928/140928130442.id-manager.el"
#+BEGIN_SRC fundamental
(quelpa '(id-manager :repo "kiwanami/emacs-id-manager" :fetcher github))
(require 'id-manager)
(setq epa-file-cache-passphrase-for-symmetric-encryption t)
(setq epa-file-select-keys 'silent)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/140928130442.id-manager.el
$ emacs -Q -f package-initialize -l 140928130442.id-manager.el
#+END_EXAMPLE

** id-managerに保存したID・パスワードにLispでアクセスする
id-managerのデータベースは
#+BEGIN_SRC emacs-lisp :results silent
(idm-load-db)
#+END_SRC
で得られます。

これはデータそのものではなくて関数オブジェクトになっています。

そこから特定のアカウント名のIDとパスワードを得るには、
この関数にシンボルgetとアカウント名を渡します。

返り値は構造体で、それぞれ
- idm-record-account-id
- idm-record-password
でアクセスできます。

つまり、
データベース関数オブジェクト→構造体→ID・パスワード
の3段階になります。

たとえば .idm-db.gpg (をデコードした内容)に以下の行があるとき、

#+BEGIN_EXAMPLE
test1	testuser	testpass	2012/11/27	test1
#+END_EXAMPLE

- アカウント名: test1
- ID: testuser
- Password: testpass
- メモ: test1

となります。

#+BEGIN_SRC emacs-lisp :results silent
(let ((record (funcall (idm-load-db) 'get "test1")))
  (idm-record-account-id record)        ; => "testuser"
  (idm-record-password record)          ; => "testpass"
  )
#+END_SRC

ちなみに今日、自分のクレジットカード使用履歴を見るための
*Ruby クローラー* を作りました。

クレジットカードのサイトのパスワードはid-managerで管理されていて、
クローラーにIDとパスワードをEmacsから渡すための学びです。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-relate.php" name="id-manager"]
