#+BLOG: rubikitch
#+POSTID: 371
#+BLOG: rubikitch
#+DATE: [2014-10-27 Mon 14:57]
#+PERMALINK: noflet
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:関数内で関数を再定義(元の関数定義も参照可能)するnofletマクロ
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: 関数再定義
#+EL_PKG_NAME: noflet
#+TAGS: アドバイス
#+EL_TITLE0: 関数内でローカル関数を定義する最強の方法
#+begin: org2blog
#+TITLE: noflet.el : 関数内でローカル関数を定義する最強の方法
[includeme file="inc-package-table.php" name="noflet" where="melpa"]
** 概要
*noflet* は *flet* の強力版で、ローカル関数を定義するマクロです。

Emacs Lispにおけるローカル関数といえば、
*cl-flet* 、 *cl-labels* 、 *cl-letf* 、 *dflet* (要 *el-x* パッケージ)
を使う方法があります。

しかし、ローカル関数で元の関数を再定義する場合、
退避する必要があるのでコードがぐちゃぐちゃになってしまいます。

その問題を解決するのが *noflet* マクロです。

noflet内での関数定義においては
変数 *this-fn* が元の関数定義を保持しているので、
#+BEGIN_EXAMPLE
(funcall this-fn 引数...)
#+END_EXAMPLE
という形で元の関数にアクセスできます。

関数ローカルな *アドバイス* みたいなものともいえます。

というわけで、関数が呼び出している関数の挙動が
気に入らない場合はローカルで上書きしちゃってください。

なお、インデントを正しくしてくれるコードもあるのですが、
僕の環境(Emacs 24.4)では正しくインデントしてくれませんでした。
[includeme file="inc-package-install.php" name="noflet" where="melpa"]

#+end:
** 概要                                                             :noexport:
*noflet* は *flet* の強力版で、ローカル関数を定義するマクロです。

Emacs Lispにおけるローカル関数といえば、
*cl-flet* 、 *cl-labels* 、 *cl-letf* 、 *dflet* (要 *el-x* パッケージ)
を使う方法があります。

しかし、ローカル関数で元の関数を再定義する場合、
退避する必要があるのでコードがぐちゃぐちゃになってしまいます。

その問題を解決するのが *noflet* マクロです。

noflet内での関数定義においては
変数 *this-fn* が元の関数定義を保持しているので、
#+BEGIN_EXAMPLE
(funcall this-fn 引数...)
#+END_EXAMPLE
という形で元の関数にアクセスできます。

関数ローカルな *アドバイス* みたいなものともいえます。

というわけで、関数が呼び出している関数の挙動が
気に入らない場合はローカルで上書きしちゃってください。

なお、インデントを正しくしてくれるコードもあるのですが、
僕の環境(Emacs 24.4)では正しくインデントしてくれませんでした。

** 使用例
dfletやcl-letfといった旧来の書き方と比較してみてください。

いかにすんなりと記述できるかがわかります。

#+BEGIN: include :file "/r/sync/junk/141027/141027144718.noflet.el"
#+BEGIN_SRC fundamental
(require 'noflet)
;;; 元の関数呼び出し
(defun hoge (x) (+ x 100))
(defun fuga (x) (+ (hoge x) 1000))
(hoge 9)                              ; => 109
(fuga 9)                              ; => 1109
;;; hogeを元の関数の結果に1足したものに置き換える
(noflet ((hoge (x) (1+ (funcall this-fn x))))
  (fuga 9))               ; => 1110
;;; hogeを引数そのものを返すように置き換える
(noflet ((hoge (x) x))
  (fuga 9))                      ; => 1009
;;; dflet(元のflet)で元の名前で呼ぶと
;;; 再帰呼び出しになって無限ループになるので退避する必要ある
(let ((orig-hoge (symbol-function 'hoge)))
  (dflet ((hoge (x) (1+ (funcall orig-hoge x))))
    (fuga 9)))                           ; => 1110
;;; cl-letfでも書けるが面倒
(cl-letf ((orig-hoge (symbol-function 'hoge))
          ((symbol-function 'hoge)
           (lambda (x) (1+ (funcall orig-hoge x)))))
  (fuga 9))                             ; => 1110

;;; 参考:cl-fletではhogeで元の関数を呼んでしまう
(cl-flet ((hoge (x) (1+ (hoge x))))
  (fuga 9))                    ; => 1109
;;; nolexfletはcl-fletの別名だがインデントを調節してくれる
(nolexflet ((hoge (x) (1+ (hoge x))))
  (fuga 9))                    ; => 1109
#+END_SRC

#+END:



# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-relate.php" name="noflet"]
