#+BLOG: rubikitch
#+POSTID: 640
#+DATE: [2014-11-30 Sun 11:26]
#+PERMALINK: stripe-buffer
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs, org-mode,
#+EL_PKG_NAME: stripe-buffer
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, relate:org, relate:dired,
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: diredやorg-modeの表を縞々カラー(ストライプ)にして見やすくする
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージstripe-bufferの紹介
#+MYTAGS: package:stripe-buffer, emacs 使い方, emacs コマンド, emacs, emacs lisp stripe-buffer, elisp stripe-buffer, emacs melpa stripe-buffer, emacs stripe-buffer 使い方, emacs stripe-buffer 設定, emacs パッケージ stripe-buffer, emacs stripe-buffer スクリーンショット, relate:org, relate:dired,
#+TITLE: emacs stripe-buffer.el : diredやorg-modeの表を縞々カラー(ストライプ)にして見やすくする | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>stripe-buffer</td></tr>
<tr><td>概要(原文)</td><td>Use a different background for even and odd lines</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/sabof/stripe-buffer">https://github.com/sabof/stripe-buffer</a></td></tr>
<tr><td>バージョン</td><td>20141208.708</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:stripe-buffer/">package:stripe-buffer</a> <a href="http://rubikitch.com/tag/package:org/">package:org</a> <a href="http://rubikitch.com/tag/package:dired/">package:dired</a></td></tr>
</table>
<br />
#+END_HTML
*stripe-buffer.el* を導入すると、
行が縞々になり、目立つようになります。

*dired* や *org-mode* の表に使うと効果的です。

diredに使うと *wdired* でカーソル位置が見えなくて不便に思いがちですが、
wdired時はカーソルが表示されるので安心です。

色については以下のfaceを *M-x customize-face* でカスタマイズしてください。

- `stripe-highlight` :: ストライプの色
- `stripe-hl-line` :: 現在行の色

** stripe-buffer インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install stripe-buffer


#+end:
** 概要                                                             :noexport:
*stripe-buffer.el* を導入すると、
行が縞々になり、目立つようになります。

*dired* や *org-mode* の表に使うと効果的です。

diredに使うと *wdired* でカーソル位置が見えなくて不便に思いがちですが、
wdired時はカーソルが表示されるので安心です。

色については以下のfaceを *M-x customize-face* でカスタマイズしてください。

- `stripe-highlight` :: ストライプの色
- `stripe-hl-line` :: 現在行の色


** 設定 [[http://rubikitch.com/f/141130113055.stripe-buffer.el][141130113055.stripe-buffer.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141130/141130113055.stripe-buffer.el"
#+BEGIN_SRC fundamental
(add-hook 'dired-mode-hook 'stripe-listify-buffer)
(add-hook 'org-mode-hook 'turn-on-stripe-table-mode)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141130113055.stripe-buffer.el
$ emacs -Q -f package-initialize -l 141130113055.stripe-buffer.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141130112904.png
Fig1: diredがストライプ化

http://rubikitch.com/f/20141130113014.png
Fig2: org-modeの表がストライプ化
