#+BLOG: rubikitch
#+POSTID: 425
#+BLOG: rubikitch
#+DATE: [2014-11-22 Sat 03:43]
#+PERMALINK: helm-bm
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:bm.elでマークした行を一覧・絞り込み検索・検索・移動。Migemo対応
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: マーク
#+EL_PKG_NAME: helm-bm
#+TAGS: Migemo対応, helm, るびきちオススメ
#+EL_TITLE0: 複数のバッファ間の「目に見えるブックマーク」を一覧・検索・移動する最強設定！Migemo対応
#+begin: org2blog
#+TITLE: helm-bm.el : 複数のバッファ間の「目に見えるブックマーク」を一覧・検索・移動する最強設定！Migemo対応
[includeme file="inc-package-table.php" name="helm-bm" where="melpa"]

#+end:
** 概要
[[http://emacs.rubikitch.com/bm/][昨日は「目に見えるブックマーク」としてbm.elを紹介しました]] が、
今日はその *helmインターフェース* です。

*M-x bm-toggle* 、 *M-x bm-previous*, *M-x bm-next* があれば
カレントバッファ内の移動は不自由しません。

実は *M-x bm-show-all* という全bmを一覧するコマンドがありますが、
/今ならやっぱりhelmだよねー！/
ということで *helm-bm.el* を紹介します。

実はanything.el時代に *M-x anything-bm-list* があったのですが、
helmでは削除されていたので、MELPAで探して見付けたのでした。

しかも大幅にパワーアップして帰ってきました。

かつて自分が作ったものがより優れたものに
置き換わるのは嬉しい限りです。

とにかくhelm化されることで快適に検索できるようになります。

なので、bmの用途が広がり、
現在位置を記憶する以外にも
/その行の『内容』を記憶させる/
という目的にも使えるようになります。

快適設定も紹介します。

[includeme file="inc-package-install.php" name="helm-bm" where="melpa"]
** 設定 [[http://rubikitch.com/f/141122044603.helm-bm.el][141122044603.helm-bm.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141122/141122044603.helm-bm.el"
#+BEGIN_SRC fundamental
;;; bm.el初期設定
(setq-default bm-buffer-persistence nil)
(setq bm-restore-repository-on-load t)
(require 'bm)
(add-hook 'find-file-hook 'bm-buffer-restore)
(add-hook 'kill-buffer-hook 'bm-buffer-save)
(add-hook 'after-save-hook 'bm-buffer-save)
(add-hook 'after-revert-hook 'bm-buffer-restore)
(add-hook 'vc-before-checkin-hook 'bm-buffer-save)
(add-hook 'kill-emacs-hook '(lambda nil
                              (bm-buffer-save-all)
                              (bm-repository-save)))
(global-set-key (kbd "M-[") 'bm-previous)
(global-set-key (kbd "M-]") 'bm-next)

;;; helm-bm.el設定
(require 'helm-bm)
;; migemoくらいつけようね
(push '(migemo) helm-source-bm)
;; annotationはあまり使わないので仕切り線で表示件数減るの嫌
(setq helm-source-bm (delete '(multiline) helm-source-bm))

(defun bm-toggle-or-helm ()
  "2回連続で起動したらhelm-bmを実行させる"
  (interactive)
  (bm-toggle)
  (when (eq last-command 'bm-toggle-or-helm)
    (helm-bm)))
(global-set-key (kbd "M-SPC") 'bm-toggle-or-helm)

;;; これがないとemacs -Qでエラーになる。おそらくバグ。
(require 'compile)
#+END_SRC

#+END:


** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141122044603.helm-bm.el
$ emacs -Q -f package-initialize -l 141122044603.helm-bm.el
#+END_EXAMPLE

提供するコマンドは *M-x helm-bm* のみです。

アクションは以下のものです。

- その場所に移動(デフォルト)
- bmを削除(C-SPCで候補をマークすることで複数可)
- annotation(bmでつけられるコメント)を編集
- カレントバッファ内の全bmを削除(候補とは無関係)
- 全バッファの全bmを削除(候補とは無関係)

デフォルトの設定から、3点を改良しました。

- [[http://emacs.rubikitch.com/migemo/][Migemo]] に対応させた
- 表示件数を増やした
- M-SPC M-SPCで起動させた

初期設定ではM-SPCにM-x bm-toggleを割り当てていましたが、
2回連続で実行すると元の状態に戻ります。

そこで、2回連続M-SPCを押すと *M-x helm-bm* を
起動させるようにすると、かなり快適になります。


http://rubikitch.com/f/20141122050546.png
Fig1: bmをhelm + migemoで絞り込み！
[includeme file="inc-package-relate.php" name="helm-bm"]
