#+BLOG: rubikitch
#+POSTID: 412
#+BLOG: rubikitch
#+DATE: [2014-11-16 Sun 10:50]
#+PERMALINK: helm-package
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:パッケージを絞り込み検索して説明を見たりインストールしたり
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: パッケージ管理
#+EL_PKG_NAME: helm-package
#+TAGS: helm, ソース解読推奨
#+EL_TITLE0: パッケージをhelmインターフェースで即座に見付けてインストール
#+begin: org2blog
#+TITLE: helm-package.el : パッケージをhelmインターフェースで即座に見付けてインストール
[includeme file="inc-package-table.php" name="helm-package" where="melpa"]
** 概要
あなたが
「こんな機能欲しいな」
と思ったとき、なにかパッケージをインストールします。

そのとき、2000を超える豊富なMELPAパッケージ群は大きな味方になります。

これだけあれば、たいていの場合、欲しい機能はすでに存在します。

どうやって探すかというと、標準の方法では *M-x list-packages* を使いますが、
isearchやoccurによる方法だと、絞り込み検索ができなかったりするので、
やや不便です。

そんなときに役立つのが *helm* インターフェースです。

*M-x helm-package* こそ、欲しいパッケージを見付ける決定打になります。

これは、パッケージ名、説明文をhelmで絞り込み検索するので、
キーワードにマッチするパッケージを一覧してくれます。

RETでそのパッケージをインストール、C-zでその説明文が見られます。
[includeme file="inc-package-install.php" name="helm-package" where="melpa"]

#+end:
** 概要                                                             :noexport:
あなたが
「こんな機能欲しいな」
と思ったとき、なにかパッケージをインストールします。

そのとき、2000を超える豊富なMELPAパッケージ群は大きな味方になります。

これだけあれば、たいていの場合、欲しい機能はすでに存在します。

どうやって探すかというと、標準の方法では *M-x list-packages* を使いますが、
isearchやoccurによる方法だと、絞り込み検索ができなかったりするので、
やや不便です。

そんなときに役立つのが *helm* インターフェースです。

*M-x helm-package* こそ、欲しいパッケージを見付ける決定打になります。

これは、パッケージ名、説明文をhelmで絞り込み検索するので、
キーワードにマッチするパッケージを一覧してくれます。

RETでそのパッケージをインストール、C-zでその説明文が見られます。
** 設定 [[http://rubikitch.com/f/141116105554.helm-package.el][141116105554.helm-package.el(以下のコードと同一)]]
パッケージの基本設定をすれば十分です。

#+BEGIN: include :file "/r/sync/junk/141116/141116105554.helm-package.el"
#+BEGIN_SRC fundamental
(add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(fset 'package-desc-vers 'package--ac-desc-version)
(package-initialize)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141116105554.helm-package.el
$ emacs -Q -f package-initialize -l 141116105554.helm-package.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141116105701.png
Fig1: M-x helm-package の後に正規表現関連のパッケージを見つける

http://rubikitch.com/f/20141116105720.png
Fig2: C-zを押して説明文を表示
[includeme file="inc-package-relate.php" name="helm-package"]
