#+BLOG: rubikitch
#+POSTID: 689
#+DATE: [2014-12-09 Tue 08:06]
#+PERMALINK: smeargle
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs
#+EL_PKG_NAME: smeargle
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, relate:vc, relate:magit, emacs 変更箇所 色付け, relate:git-gutter, , emacs git blame, emacs hg blame, 
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: ファイルの各行の更新日時(git blame/hg blame等)によって色分けする
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージsmeargleの紹介
#+MYTAGS: package:smeargle, emacs 使い方, emacs コマンド, emacs, emacs lisp smeargle, elisp smeargle, emacs melpa smeargle, emacs smeargle 使い方, emacs smeargle 設定, emacs パッケージ smeargle, emacs smeargle スクリーンショット, relate:vc, relate:magit, emacs 変更箇所 色付け, relate:git-gutter, , emacs git blame, emacs hg blame, 
#+TITLE: emacs smeargle.el : ファイルの各行の更新日時(git blame/hg blame等)によって色分けする | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>smeargle</td></tr>
<tr><td>概要(原文)</td><td>Highlighting region by last updated time</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/syohex/emacs-smeargle">https://github.com/syohex/emacs-smeargle</a></td></tr>
<tr><td>バージョン</td><td>20141110.1919</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:smeargle/">package:smeargle</a> <a href="http://rubikitch.com/tag/package:vc/">package:vc</a> <a href="http://rubikitch.com/tag/package:magit/">package:magit</a> <a href="http://rubikitch.com/tag/package:git-gutter/">package:git-gutter</a></td></tr>
</table>
<br />
#+END_HTML

*smeargle.el* は、最後に更新された部分をハイライトします。

変更された時期によって色が徐々に変わっていきます。

古くなればなるほど白っぽくなり、
新しくなればなるほど黒っぽくなります。

サポートされているバージョン管理システムは
 *git* と *mercurial* です。

Vimの同名のプラグインの移植版です。

ちなみにsmeargleはポケモンのドーブルの英名です。

同じ作者による *git-gutter.el* と組み合わせるともっとよいです。

** smeargle インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install smeargle


#+end:
** 概要                                                             :noexport:

*smeargle.el* は、最後に更新された部分をハイライトします。

変更された時期によって色が徐々に変わっていきます。

古くなればなるほど白っぽくなり、
新しくなればなるほど黒っぽくなります。

サポートされているバージョン管理システムは
 *git* と *mercurial* です。

Vimの同名のプラグインの移植版です。

ちなみにsmeargleはポケモンのドーブルの英名です。

同じ作者による *git-gutter.el* と組み合わせるともっとよいです。


** 設定 [[http://rubikitch.com/f/141209080439.smeargle.el][141209080439.smeargle.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141209/141209080439.smeargle.el"
#+BEGIN_SRC fundamental
;;; 色の設定
(setq smeargle-age-colors
      '((0 . nil)
        (1 . "grey5")
        (2 . "grey10")
        (3 . "grey15")
        (4 . "grey20")
        (5 . "grey25")
        (6 . "grey30")
        (7 . "grey30")))
(setq smeargle-colors
      '((older-than-1day . nil)
        (older-than-3day . "grey5")
        (older-than-1week . "grey10")
        (older-than-2week . "grey15")
        (older-than-1month . "grey20")
        (older-than-3month . "grey25")
        (older-than-6month . "grey30")
        (older-than-1year . "grey35")))

(global-set-key (kbd "C-x v s") 'smeargle)
(global-set-key (kbd "C-x v c") 'smeargle-commits)

;; ファイルを開いたときに実行
(add-hook 'find-file-hook 'smeargle)

;; 保存後に実行
(add-hook 'after-save-hook 'smeargle)
#+END_SRC

#+END:

*** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141209080439.smeargle.el
$ emacs -Q -f package-initialize -l 141209080439.smeargle.el
#+END_EXAMPLE

- *M-x smeargle* :: 最終更新日時でハイライト
- *M-x smeargle-commits* :: 変更してからの時間でハイライト
- *M-x smeargle-clear* :: smeargleの色付けを解除する

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141209081601.png
Fig1: 変更時期に合わせて色付け
