#+BLOG: rubikitch
#+POSTID: 732
#+DATE: [2014-12-17 Wed 07:35]
#+PERMALINK: imenu-anywhere
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs, helm, ido
#+EL_PKG_NAME: imenu-anywhere
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, emacs imenu, relate:helm, package:ido, imenu ido, relate:idomenu, relate:ido-vertical-mode, relate:imenu-list, relate:imenus, package:ido-vertical-mode, relate:ido-vertical-mode, emacs iswitchb imenu, emacs imenu ido, emacs imenu helm, 同一メジャーモードのバッファの関数一覧を表示, emacs imenu カイゼン, emacs imenu 強化, anything-imenu, helm-imenu, ファイル内の関数一覧を表示, バッファ内の関数一覧を表示, 特定の関数を抽出, 関数定義へジャンプ, バッファ内の特定箇所に直接移動
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: 【Windows安心】簡易関数定義ジャンプimenuをido/helm化した上で他のファイルまで拡張する！
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージimenu-anywhereの紹介
#+MYTAGS: package:imenu-anywhere, emacs 使い方, emacs コマンド, emacs, emacs lisp imenu-anywhere, elisp imenu-anywhere, emacs melpa imenu-anywhere, emacs imenu-anywhere 使い方, emacs imenu-anywhere 設定, emacs パッケージ imenu-anywhere, emacs imenu-anywhere スクリーンショット, emacs imenu, relate:helm, package:ido, imenu ido, relate:idomenu, relate:ido-vertical-mode, relate:imenu-list, relate:imenus, package:ido-vertical-mode, relate:ido-vertical-mode, emacs iswitchb imenu, emacs imenu ido, emacs imenu helm, 同一メジャーモードのバッファの関数一覧を表示, emacs imenu カイゼン, emacs imenu 強化, anything-imenu, helm-imenu, ファイル内の関数一覧を表示, バッファ内の関数一覧を表示, 特定の関数を抽出, 関数定義へジャンプ, バッファ内の特定箇所に直接移動
#+TAGS: package:imenu-anywhere, emacs 使い方, emacs コマンド, emacs, emacs lisp imenu-anywhere, elisp imenu-anywhere, emacs melpa imenu-anywhere, emacs imenu-anywhere 使い方, emacs imenu-anywhere 設定, emacs パッケージ imenu-anywhere, emacs imenu-anywhere スクリーンショット, emacs imenu, relate:helm, package:ido, imenu ido, relate:idomenu, relate:ido-vertical-mode, relate:imenu-list, relate:imenus, package:ido-vertical-mode, relate:ido-vertical-mode, emacs iswitchb imenu, emacs imenu ido, emacs imenu helm, 同一メジャーモードのバッファの関数一覧を表示, emacs imenu カイゼン, emacs imenu 強化, anything-imenu, helm-imenu, ファイル内の関数一覧を表示, バッファ内の関数一覧を表示, 特定の関数を抽出, 関数定義へジャンプ, バッファ内の特定箇所に直接移動, Emacs, helm, ido, imenu-anywhere.el, M-x imenu, imenu, TAGS, タグファイル, Windows, ido, helm, imenu-anywhere.el, M-x imenu, imenu, TAGS, タグファイル, Windows, ido, helm, M-x helm-imenu-anywhere, with-helm-current-buffer, M-x ido-imenu-anywhere
#+TITLE: emacs imenu-anywhere.el : 【Windows安心】簡易関数定義ジャンプimenuをido/helm化した上で他のファイルまで拡張する！ | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>imenu-anywhere</td></tr>
<tr><td>概要(原文)</td><td>ido/helm imenu tag selection across all buffers with the same mode</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/vitoshka/imenu-anywhere">https://github.com/vitoshka/imenu-anywhere</a></td></tr>
<tr><td>バージョン</td><td>20150204.50</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:imenu-anywhere/">package:imenu-anywhere</a> <a href="http://rubikitch.com/tag/package:helm/">package:helm</a> <a href="http://rubikitch.com/tag/package:idomenu/">package:idomenu</a> <a href="http://rubikitch.com/tag/package:ido-vertical-mode/">package:ido-vertical-mode</a> <a href="http://rubikitch.com/tag/package:imenu-list/">package:imenu-list</a> <a href="http://rubikitch.com/tag/package:imenus/">package:imenus</a> <a href="http://rubikitch.com/tag/package:ido-vertical-mode/">package:ido-vertical-mode</a></td></tr>
</table>
<br />
#+END_HTML
<2015-04-09 Thu> [[http://rubikitch.com/2015/04/09/imenus/][imenus.el]] の方がoccur/helm-swoopもできたりとより便利です。

<2014-12-22 Mon>バグ修正！

*imenu-anywhere.el* は、 *M-x imenu* を大きく進化させます。

*imenu* は、 *TAGS* ファイルを作らなくても
気楽にタグジャンプできますが、
現在のファイルに限定されています。

*タグファイル* なしで関数定義にジャンプできるのは、とても手軽だし、
外部プログラムのインストールに手間取る *Windows* 環境だと嬉しいものです。

Windowsじゃなくてもわざわざ手動で
タグファイルを作るのが面倒な場合もあります。

そういう場合にimenuは特効薬となります。

しかし…

複数のファイルにまたがるタグジャンプが
できないのは不便ですね。

しかも標準のimenuは候補選択がしづらいです。

そこでimenu-anywhere.elはこの2つの欠点を排除します！

第一にimenu-anywhere.elは同一メジャーモードの
すべてのバッファまでimenuの範囲を広げます。

第二に、imenuを *ido* / *helm* インターフェースにして
候補選択しやすくします。

特に[[http://rubikitch.com/2014/12/16/smex/][idoのあいまいマッチは強力]] で
各文字間のに任意の文字が入ることを許されています。

しかもウィンドウ構成を変更しないので
目線が移動しないメリットもあります。

候補が比較的少数で、
単一の情報源で、
ひとつのアクションで、
[[http://rubikitch.com/2014/08/20/migemo/][Migemo]] らないならば、
helmよりもidoの方が優れていると僕は考えています。

helmはあくまで複数の情報源を同時に扱えることが魅力なんですから。
** imenu-anywhere インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install imenu-anywhere


#+end:
** 概要                                                             :noexport:
<2015-04-09 Thu> [[http://rubikitch.com/2015/04/09/imenus/][imenus.el]] の方がoccur/helm-swoopもできたりとより便利です。

<2014-12-22 Mon>バグ修正！

*imenu-anywhere.el* は、 *M-x imenu* を大きく進化させます。

*imenu* は、 *TAGS* ファイルを作らなくても
気楽にタグジャンプできますが、
現在のファイルに限定されています。

*タグファイル* なしで関数定義にジャンプできるのは、とても手軽だし、
外部プログラムのインストールに手間取る *Windows* 環境だと嬉しいものです。

Windowsじゃなくてもわざわざ手動で
タグファイルを作るのが面倒な場合もあります。

そういう場合にimenuは特効薬となります。

しかし…

複数のファイルにまたがるタグジャンプが
できないのは不便ですね。

しかも標準のimenuは候補選択がしづらいです。

そこでimenu-anywhere.elはこの2つの欠点を排除します！

第一にimenu-anywhere.elは同一メジャーモードの
すべてのバッファまでimenuの範囲を広げます。

第二に、imenuを *ido* / *helm* インターフェースにして
候補選択しやすくします。

特に[[http://rubikitch.com/2014/12/16/smex/][idoのあいまいマッチは強力]] で
各文字間のに任意の文字が入ることを許されています。

しかもウィンドウ構成を変更しないので
目線が移動しないメリットもあります。

候補が比較的少数で、
単一の情報源で、
ひとつのアクションで、
[[http://rubikitch.com/2014/08/20/migemo/][Migemo]] らないならば、
helmよりもidoの方が優れていると僕は考えています。

helmはあくまで複数の情報源を同時に扱えることが魅力なんですから。
** <2014-12-17 Wed>バグあり→<2014-12-22 Mon>修正
<2014-12-22 Mon>このバグは修正されましたが、
imenuをrequireする必要があります。

<2015-01-17 Sat>現時点ではバグにより.elを読み込まないと
*M-x helm-imenu-anywhere* は動作しません。

imenu-anywhere.elで
#+BEGIN_SRC emacs-lisp :results silent
(eval-when-compile (require 'helm))
#+END_SRC
が入っていないせいで、
マクロ *with-helm-current-buffer* が関数として
バイトコンパイルされているからです。

*M-x ido-imenu-anywhere* を使う人はrequireは不要です。

@yewtonさん、情報提供ありがとうございます。

** 設定 [[http://rubikitch.com/f/141217072721.imenu-anywhere.1.el][141217072721.imenu-anywhere.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141217/141217072721.imenu-anywhere.1.el"
#+BEGIN_SRC fundamental
(require 'imenu)
(setq ido-enable-flex-matching t)       ;あいまいマッチ
(global-set-key (kbd "C-.") 'ido-imenu-anywhere)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141217072721.imenu-anywhere.1.el
$ emacs -Q -f package-initialize -l 141217072721.imenu-anywhere.1.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141217073454.png
Fig1: idoのあいまいマッチでimenu！

http://rubikitch.com/f/20141217075121.png
Fig2: 他バッファの関数を選択！

http://rubikitch.com/f/20141217121147.png
Fig3: M-x helm-imenu-anywhere

