#+BLOG: rubikitch
#+POSTID: 507
#+BLOG: rubikitch
#+DATE: [2014-12-19 Fri 09:40]
#+PERMALINK: helm-migemo
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:今はhelm-migemo-modeとしてhelm本体に組み込まれているので不要
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: 検索
#+EL_PKG_NAME: helm-migemo
#+TAGS: helm, Migemo対応
#+EL_TITLE0: helmで正しくMigemoを動作させる！
#+begin: org2blog
#+TITLE: helm-migemo.el : helmで正しくMigemoを動作させる！
[includeme file="inc-package-table.php" name="helm-migemo" where="melpa"]
** 概要
<2015-10-03 Sat> helm本体にhelm-migemo-modeとして組み込まれたので不要です。

<2015-09-07 Mon> [[https://github.com/emacs-helm/helm/commit/b26db37][8/21の変更]] の煽りを受け、設定を更新しました。「補足」追加。

*helm-migemo.el* は、かつて僕が作った *anything-migemo.el* を
[[http://sheephead.homelinux.org/][myuheさん ]]がhelmに移植したものです。

これを使えばhelmのMigemo対応情報源にてMigemo検索できるようになります。

しかし、helmが *lexical-binding* 対応になったときから
そのままでは動作しなくなってしまいました。

本設定を使えば引き続きMigemoで絞り込めるようになります。

Migemo対応情報源ではMigemo使えるが反面、
正規表現が無効になってしまいます。

*helm-swoop* などではそれが顕著に出てくるので注意してください。
<2014-12-25 Thu> [[http://emacs.rubikitch.com/helm-swoop/][Emacs Advent Calendar 2014にてhelm-swoopについて書きました！]] 

情報源をMigemoに対応するには(migemo)を加えます。
[[http://emacs.rubikitch.com/helm-bm/][helm-bmの例を参考にしてください]] 。
[includeme file="inc-package-install.php" name="helm-migemo" where="melpa"]

#+end:
** 概要                                                             :noexport:
<2015-10-03 Sat> helm本体にhelm-migemo-modeとして組み込まれたので不要です。

<2015-09-07 Mon> [[https://github.com/emacs-helm/helm/commit/b26db37][8/21の変更]] の煽りを受け、設定を更新しました。「補足」追加。

*helm-migemo.el* は、かつて僕が作った *anything-migemo.el* を
[[http://sheephead.homelinux.org/][myuheさん ]]がhelmに移植したものです。

これを使えばhelmのMigemo対応情報源にてMigemo検索できるようになります。

しかし、helmが *lexical-binding* 対応になったときから
そのままでは動作しなくなってしまいました。

本設定を使えば引き続きMigemoで絞り込めるようになります。

Migemo対応情報源ではMigemo使えるが反面、
正規表現が無効になってしまいます。

*helm-swoop* などではそれが顕著に出てくるので注意してください。
<2014-12-25 Thu> [[http://emacs.rubikitch.com/helm-swoop/][Emacs Advent Calendar 2014にてhelm-swoopについて書きました！]] 

情報源をMigemoに対応するには(migemo)を加えます。
[[http://emacs.rubikitch.com/helm-bm/][helm-bmの例を参考にしてください]] 。

** 設定 [[http://rubikitch.com/f/helm-migemo-fix.1.el][helm-migemo-fix.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/emacs/lisp/helm-migemo-fix.1.el"
#+BEGIN_SRC fundamental
(require 'helm-migemo)
;;; この修正が必要
(with-eval-after-load "helm-migemo"
  (defun helm-compile-source--candidates-in-buffer (source)
    (helm-aif (assoc 'candidates-in-buffer source)
        (append source
                `((candidates
                   . ,(or (cdr it)
                          (lambda ()
                            ;; Do not use `source' because other plugins
                            ;; (such as helm-migemo) may change it
                            (helm-candidates-in-buffer (helm-get-current-source)))))
                  (volatile) (match identity)))
      source))
  ;; [2015-09-06 Sun]helm-match-plugin -> helm-multi-match変更の煽りを受けて
  (defalias 'helm-mp-3-get-patterns 'helm-mm-3-get-patterns)
  (defalias 'helm-mp-3-search-base 'helm-mm-3-search-base))
#+END_SRC

#+END:

** 実行方法
動作させるには、migemoの設定をロードしてください。

#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/helm-migemo-fix.1.el
$ emacs -Q -f package-initialize -l your-migemo-settings.el -l helm-migemo-fix.1.el
#+END_EXAMPLE
# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141219095040.png
Fig1: Migemoで絞り込み

** <2015-09-07 Mon>補足:なぜ関数再定義が必要か
Twitterで helm-compile-source--candidates-in-buffer の修正を外すと動作した
という声がありましたが、この修正は必要です。

確かに修正を施さなくても動く場合がありますが、
candidates-in-bufferは動作しません。

#+BEGIN_SRC emacs-lisp :results silent
(helm '(((name . "candidates")
         (candidates "ほげ" "ふが" "hoge")
         (migemo))
        ((name . "candidates-in-buffer")
         (candidates-in-buffer)
         (init . (lambda ()
                   (with-current-buffer (helm-candidate-buffer 'global)
                     (insert "ほげ\nふが\nhoge\n"))))
         (migemo))))
#+END_SRC

上記のテストコードにおいて、hogeと入力したとき
双方のsourceともに「ほげ」「hoge」と表示されるのが正しいです。

修正を外した場合は後者の「ほげ」が表示されません。
[includeme file="inc-package-relate.php" name="helm-migemo"]
