#+BLOG: rubikitch
#+POSTID: 471
#+BLOG: rubikitch
#+DATE: [2014-12-09 Tue 08:06]
#+PERMALINK: smeargle
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:コード各行が更新日時によって色分けされることで、いつ更新されたのかがわかりやすくなる
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: バージョン管理システム
#+EL_PKG_NAME: smeargle
#+TAGS: from:vim, git, hg
#+EL_TITLE0: ファイルの各行の更新日時(git blame/hg blame等)によって色分けする
#+begin: org2blog
#+TITLE: smeargle.el : ファイルの各行の更新日時(git blame/hg blame等)によって色分けする
[includeme file="inc-package-table.php" name="smeargle" where="melpa"]
** 概要

*smeargle.el* は、最後に更新された部分をハイライトします。

変更された時期によって色が徐々に変わっていきます。

古くなればなるほど白っぽくなり、
新しくなればなるほど黒っぽくなります。

サポートされているバージョン管理システムは
 *git* と *mercurial* です。

Vimの同名のプラグインの移植版です。

ちなみにsmeargleはポケモンのドーブルの英名です。

同じ作者による *git-gutter.el* と組み合わせるともっとよいです。

[includeme file="inc-package-install.php" name="smeargle" where="melpa"]

#+end:
** 概要                                                             :noexport:

*smeargle.el* は、最後に更新された部分をハイライトします。

変更された時期によって色が徐々に変わっていきます。

古くなればなるほど白っぽくなり、
新しくなればなるほど黒っぽくなります。

サポートされているバージョン管理システムは
 *git* と *mercurial* です。

Vimの同名のプラグインの移植版です。

ちなみにsmeargleはポケモンのドーブルの英名です。

同じ作者による *git-gutter.el* と組み合わせるともっとよいです。


** 設定 [[http://rubikitch.com/f/141209080439.smeargle.el][141209080439.smeargle.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141209/141209080439.smeargle.el"
#+BEGIN_SRC fundamental
;;; 色の設定
(setq smeargle-age-colors
      '((0 . nil)
        (1 . "grey5")
        (2 . "grey10")
        (3 . "grey15")
        (4 . "grey20")
        (5 . "grey25")
        (6 . "grey30")
        (7 . "grey30")))
(setq smeargle-colors
      '((older-than-1day . nil)
        (older-than-3day . "grey5")
        (older-than-1week . "grey10")
        (older-than-2week . "grey15")
        (older-than-1month . "grey20")
        (older-than-3month . "grey25")
        (older-than-6month . "grey30")
        (older-than-1year . "grey35")))

(global-set-key (kbd "C-x v s") 'smeargle)
(global-set-key (kbd "C-x v c") 'smeargle-commits)

;; ファイルを開いたときに実行
(add-hook 'find-file-hook 'smeargle)

;; 保存後に実行
(add-hook 'after-save-hook 'smeargle)
#+END_SRC

#+END:

*** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141209080439.smeargle.el
$ emacs -Q -f package-initialize -l 141209080439.smeargle.el
#+END_EXAMPLE

- *M-x smeargle* :: 最終更新日時でハイライト
- *M-x smeargle-commits* :: 変更してからの時間でハイライト
- *M-x smeargle-clear* :: smeargleの色付けを解除する

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141209081601.png
Fig1: 変更時期に合わせて色付け
[includeme file="inc-package-relate.php" name="smeargle"]
