#+BLOG: rubikitch
#+POSTID: 475
#+BLOG: rubikitch
#+DATE: [2014-12-10 Wed 04:32]
#+PERMALINK: multicolumn
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:C-x 4 4でウィンドウを分割した後にfollow-modeにする。C-x 3で予め決められた桁数によって左右分割しまくる。
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ウィンドウ操作
#+EL_PKG_NAME: multicolumn
#+TAGS: マイナーモード, 
#+EL_TITLE0: 【ワイドディスプレイ支援】follow-modeで表示行数を何倍にも増やす方法＋α
#+begin: org2blog
#+TITLE: multicolumn.el : 【ワイドディスプレイ支援】follow-modeで表示行数を何倍にも増やす方法＋α
[includeme file="inc-package-table.php" name="multicolumn" where="melpa"]
** 概要

multicolumn.elは、昨今の *ワイドディスプレイ* を有効活用するelispです。

ワイドディスプレイといえば、
Emacs標準機能の *M-x follow-mode* を
思い浮かべる方がいるでしょう。

そう、multicolumn.elはfollow-modeをもうちょっと使いやすくするものです。

*follow-mode* とは、左右分割したウィンドウに
前のウィンドウで表示されている内容の続きを表示することで
疑似的に超縦長ディスプレイを実現させます。

長いコードを1画面に治める様は圧巻です！

作者は2つのディスプレイにそれぞれ6分割ウィンドウを用意し、
888行のコードを一瞥しているらしいです…(スゴイ

いろいろなコマンドが用意されていますが、使いこなすには
/たった2つのコマンドを覚えれば十分です！/

ウィンドウ構成を管理する独自コードが書かれていますが、
*winner-mode* を使ってしまえばそんなの不要です。

C-x 4プレフィクスキーにいくつかのコマンドが用意されていますが、
それについても操作性の観点から不要です。
[includeme file="inc-package-install.php" name="multicolumn" where="melpa"]

#+end:
** 概要                                                             :noexport:

multicolumn.elは、昨今の *ワイドディスプレイ* を有効活用するelispです。

ワイドディスプレイといえば、
Emacs標準機能の *M-x follow-mode* を
思い浮かべる方がいるでしょう。

そう、multicolumn.elはfollow-modeをもうちょっと使いやすくするものです。

*follow-mode* とは、左右分割したウィンドウに
前のウィンドウで表示されている内容の続きを表示することで
疑似的に超縦長ディスプレイを実現させます。

長いコードを1画面に治める様は圧巻です！

作者は2つのディスプレイにそれぞれ6分割ウィンドウを用意し、
888行のコードを一瞥しているらしいです…(スゴイ

いろいろなコマンドが用意されていますが、使いこなすには
/たった2つのコマンドを覚えれば十分です！/

ウィンドウ構成を管理する独自コードが書かれていますが、
*winner-mode* を使ってしまえばそんなの不要です。

C-x 4プレフィクスキーにいくつかのコマンドが用意されていますが、
それについても操作性の観点から不要です。

** 設定 [[http://rubikitch.com/f/141210042347.multicolumn.1.el][141210042347.multicolumn.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141210/141210042347.multicolumn.1.el"
#+BEGIN_SRC fundamental
(multicolumn-global-mode 1)
(setq multicolumn-min-width 72)
(define-key multicolumn-map (kbd "C-x 4 4")
  'multicolumn-delete-other-windows-and-split-with-follow-mode)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141210042347.multicolumn.1.el
$ emacs -Q -f package-initialize -l 141210042347.multicolumn.1.el
#+END_EXAMPLE
** C-x 3をカイゼン
*M-x multicolumn-global-mode* でマイナーモードを有効にすれば、
C-x 3が *M-x multicolumn-delete-other-windows-and-split*
に変更されます。

元来C-x 3はただ左右分割するだけですが、
予め定められた桁数 (*multicolumn-min-width*) によって
一気に左右分割しまくります。

初期値は72です。

たとえば桁数が220 (*(frame-width)* の値) のとき、
一気に3分割されます。

また、数引数で分割数を指定できます。

C-4 C-x 3で3分割というふうにです。
** 分割後にfollow-modeにする
もうひとつ重要なコマンドが
*M-x multicolumn-delete-other-windows-and-split-with-follow-mode*
で、ウィンドウを分割した後、そのバッファをfollow-modeにします。

長い…

本設定ではC-x 4 4に割り当てています。


# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141210050410.png
Fig1: C-x 4 4でウィンドウが分割されてfollow-modeに！

[includeme file="inc-package-relate.php" name="multicolumn"]
