#+BLOG: rubikitch
#+POSTID: 461
#+BLOG: rubikitch
#+DATE: [2014-12-07 Sun 03:47]
#+PERMALINK: google-translate
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION: M-x google-translate-enja-or-jaenは現在のセンテンス、region、入力文字列、引数を言語自動判別で英訳・和訳します。
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: 辞書・翻訳
#+EL_PKG_NAME: google-translate
#+TAGS: google, るびきちオススメ, 初心者安心
#+EL_TITLE0: 【設定パワーアップ】Google翻訳で言語自動判別しつつ英訳・和訳する！
#+begin: org2blog
#+TITLE: google-translate.el : 【設定パワーアップ】Google翻訳で言語自動判別しつつ英訳・和訳する！
[includeme file="inc-package-table.php" name="google-translate" where="melpa"]
** 概要
<2014-12-30 Tue>設定を大幅パワーアップ！！！！

*google-translate.el* は、Google翻訳APIを使って
様々な言語の翻訳を行います。

しかも高速に動作します！

英語に悩んでいる人には朗報ですね。

本設定では、英語・日本語の自動判別をしたコマンドを用意しました。

ASCII文字でのみ構成されている場合は英語とみなします。

C-c tに割り当てた *M-x google-translate-enja-or-jaen* は、
以下の挙動を取ります。

- C-c t (regionあり): regionを翻訳
- C-c t (regionなし): 現在のセンテンスを翻訳(NEW!!)
- C-u C-c t: 入力文字列を翻訳(NEW!!)
- (google-translate-enja-or-jaen "english string"): 英語→日本語
- (google-translate-enja-or-jaen "日本語文字列"): 日本語→英語


もし英語・日本語以外の言語を使うならば、
*google-translate-translation-directions-alist* に
様々な言語を設定し、 *M-x google-translate-smooth-translate* を
直接使いましょう。

[includeme file="inc-package-install.php" name="google-translate" where="melpa"]

#+end:
** 概要                                                             :noexport:
<2014-12-30 Tue>設定を大幅パワーアップ！！！！

*google-translate.el* は、Google翻訳APIを使って
様々な言語の翻訳を行います。

しかも高速に動作します！

英語に悩んでいる人には朗報ですね。

本設定では、英語・日本語の自動判別をしたコマンドを用意しました。

ASCII文字でのみ構成されている場合は英語とみなします。

C-c tに割り当てた *M-x google-translate-enja-or-jaen* は、
以下の挙動を取ります。

- C-c t (regionあり): regionを翻訳
- C-c t (regionなし): 現在のセンテンスを翻訳(NEW!!)
- C-u C-c t: 入力文字列を翻訳(NEW!!)
- (google-translate-enja-or-jaen "english string"): 英語→日本語
- (google-translate-enja-or-jaen "日本語文字列"): 日本語→英語


もし英語・日本語以外の言語を使うならば、
*google-translate-translation-directions-alist* に
様々な言語を設定し、 *M-x google-translate-smooth-translate* を
直接使いましょう。


** 設定 [[http://rubikitch.com/f/141230072954.google-translate-2.el][141230072954.google-translate-2.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141230/141230072954.google-translate-2.el"
#+BEGIN_SRC fundamental
(require 'google-translate)

(defvar google-translate-english-chars "[:ascii:]’“”–"
  "これらの文字が含まれているときは英語とみなす")
(defun google-translate-enja-or-jaen (&optional string)
  "regionか、現在のセンテンスを言語自動判別でGoogle翻訳する。"
  (interactive)
  (setq string
        (cond ((stringp string) string)
              (current-prefix-arg
               (read-string "Google Translate: "))
              ((use-region-p)
               (buffer-substring (region-beginning) (region-end)))
              (t
               (save-excursion
                 (let (s)
                   (forward-char 1)
                   (backward-sentence)
                   (setq s (point))
                   (forward-sentence)
                   (buffer-substring s (point)))))))
  (let* ((asciip (string-match
                  (format "\\`[%s]+\\'" google-translate-english-chars)
                  string)))
    (run-at-time 0.1 nil 'deactivate-mark)
    (google-translate-translate
     (if asciip "en" "ja")
     (if asciip "ja" "en")
     string)))
(global-set-key (kbd "C-c t") 'google-translate-enja-or-jaen)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141230072954.google-translate-2.el
$ emacs -Q -f package-initialize -l 141230072954.google-translate-2.el
#+END_EXAMPLE


# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141207040527.png
Fig1: 翻訳！
[includeme file="inc-package-relate.php" name="google-translate"]
