#+BLOG: rubikitch
#+POSTID: 493
#+BLOG: rubikitch
#+DATE: [2014-12-17 Wed 07:35]
#+PERMALINK: imenu-anywhere
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:imenuをido/helmインターフェースにして、同一メジャーモードの他のファイルにまで探索範囲を広げる。imenusの方がおすすめ。
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: タグジャンプ
#+EL_PKG_NAME: imenu-anywhere
#+TAGS: imenu, helm, ido
#+EL_TITLE0: 【Windows安心】簡易関数定義ジャンプimenuをido/helm化した上で他のファイルまで拡張する！
#+begin: org2blog
#+TITLE: imenu-anywhere.el : 【Windows安心】簡易関数定義ジャンプimenuをido/helm化した上で他のファイルまで拡張する！
[includeme file="inc-package-table.php" name="imenu-anywhere" where="melpa"]
** 概要
<2015-04-09 Thu> [[http://emacs.rubikitch.com/imenus/][imenus.el]] の方がoccur/helm-swoopもできたりとより便利です。

<2014-12-22 Mon>バグ修正！

*imenu-anywhere.el* は、 *M-x imenu* を大きく進化させます。

*imenu* は、 *TAGS* ファイルを作らなくても
気楽にタグジャンプできますが、
現在のファイルに限定されています。

*タグファイル* なしで関数定義にジャンプできるのは、とても手軽だし、
外部プログラムのインストールに手間取る *Windows* 環境だと嬉しいものです。

Windowsじゃなくてもわざわざ手動で
タグファイルを作るのが面倒な場合もあります。

そういう場合にimenuは特効薬となります。

しかし…

複数のファイルにまたがるタグジャンプが
できないのは不便ですね。

しかも標準のimenuは候補選択がしづらいです。

そこでimenu-anywhere.elはこの2つの欠点を排除します！

第一にimenu-anywhere.elは同一メジャーモードの
すべてのバッファまでimenuの範囲を広げます。

第二に、imenuを *ido* / *helm* インターフェースにして
候補選択しやすくします。

特に[[http://emacs.rubikitch.com/smex/][idoのあいまいマッチは強力]] で
各文字間のに任意の文字が入ることを許されています。

しかもウィンドウ構成を変更しないので
目線が移動しないメリットもあります。

候補が比較的少数で、
単一の情報源で、
ひとつのアクションで、
[[http://emacs.rubikitch.com/migemo/][Migemo]] らないならば、
helmよりもidoの方が優れていると僕は考えています。

helmはあくまで複数の情報源を同時に扱えることが魅力なんですから。
[includeme file="inc-package-install.php" name="imenu-anywhere" where="melpa"]

#+end:
** 概要                                                             :noexport:
<2015-04-09 Thu> [[http://emacs.rubikitch.com/imenus/][imenus.el]] の方がoccur/helm-swoopもできたりとより便利です。

<2014-12-22 Mon>バグ修正！

*imenu-anywhere.el* は、 *M-x imenu* を大きく進化させます。

*imenu* は、 *TAGS* ファイルを作らなくても
気楽にタグジャンプできますが、
現在のファイルに限定されています。

*タグファイル* なしで関数定義にジャンプできるのは、とても手軽だし、
外部プログラムのインストールに手間取る *Windows* 環境だと嬉しいものです。

Windowsじゃなくてもわざわざ手動で
タグファイルを作るのが面倒な場合もあります。

そういう場合にimenuは特効薬となります。

しかし…

複数のファイルにまたがるタグジャンプが
できないのは不便ですね。

しかも標準のimenuは候補選択がしづらいです。

そこでimenu-anywhere.elはこの2つの欠点を排除します！

第一にimenu-anywhere.elは同一メジャーモードの
すべてのバッファまでimenuの範囲を広げます。

第二に、imenuを *ido* / *helm* インターフェースにして
候補選択しやすくします。

特に[[http://emacs.rubikitch.com/smex/][idoのあいまいマッチは強力]] で
各文字間のに任意の文字が入ることを許されています。

しかもウィンドウ構成を変更しないので
目線が移動しないメリットもあります。

候補が比較的少数で、
単一の情報源で、
ひとつのアクションで、
[[http://emacs.rubikitch.com/migemo/][Migemo]] らないならば、
helmよりもidoの方が優れていると僕は考えています。

helmはあくまで複数の情報源を同時に扱えることが魅力なんですから。
** <2014-12-17 Wed>バグあり→<2014-12-22 Mon>修正
<2014-12-22 Mon>このバグは修正されましたが、
imenuをrequireする必要があります。

<2015-01-17 Sat>現時点ではバグにより.elを読み込まないと
*M-x helm-imenu-anywhere* は動作しません。

imenu-anywhere.elで
#+BEGIN_SRC emacs-lisp :results silent
(eval-when-compile (require 'helm))
#+END_SRC
が入っていないせいで、
マクロ *with-helm-current-buffer* が関数として
バイトコンパイルされているからです。

*M-x ido-imenu-anywhere* を使う人はrequireは不要です。

@yewtonさん、情報提供ありがとうございます。

** 設定 [[http://rubikitch.com/f/141217072721.imenu-anywhere.1.el][141217072721.imenu-anywhere.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141217/141217072721.imenu-anywhere.1.el"
#+BEGIN_SRC fundamental
(require 'imenu)
(setq ido-enable-flex-matching t)       ;あいまいマッチ
(global-set-key (kbd "C-.") 'ido-imenu-anywhere)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141217072721.imenu-anywhere.1.el
$ emacs -Q -f package-initialize -l 141217072721.imenu-anywhere.1.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141217073454.png
Fig1: idoのあいまいマッチでimenu！

http://rubikitch.com/f/20141217075121.png
Fig2: 他バッファの関数を選択！

http://rubikitch.com/f/20141217121147.png
Fig3: M-x helm-imenu-anywhere

[includeme file="inc-package-relate.php" name="imenu-anywhere"]
