#+BLOG: rubikitch
#+POSTID: 483
#+BLOG: rubikitch
#+DATE: [2014-12-15 Mon 07:49]
#+PERMALINK: switch-window
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:Hit-a-Hintでウィンドウ切り替え。win-switchの方が使いやすい。
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ウィンドウ切り替え
#+EL_PKG_NAME: switch-window
#+TAGS: 
#+EL_TITLE0: ウィンドウをたくさん分割する人必携！C-x oを連発せずに直接ウィンドウを切り替える
#+begin: org2blog
#+TITLE: switch-window.el : ウィンドウをたくさん分割する人必携！C-x oを連発せずに直接ウィンドウを切り替える
[includeme file="inc-package-table.php" name="switch-window" where="melpa"]
** 概要
<2015-02-21 Sat> [[http://emacs.rubikitch.com/win-switch/][win-switch.elの方がもっと使いやすいです。]] 

*switch-window.el* は *C-x o* をカイゼンするものです。

使い方は簡単で、C-x oを *M-x switch-window* に置き換え、
通常通り使うだけです。

2分割のときはそのまま他方のウィンドウに切り替えるのですが、
3分割以上のときはasdf〜とヒント文字がつき、
それを選択することで目的のウィンドウに切り替えます。

とはいえ、3分割以上をしない人とか、
*other-window* をC-tのように1ストロークに割り当てている人は
あまり恩恵を感じないかもしれません。

よくウィンドウを分割する人は [[http://emacs.rubikitch.com/owdriver/][owdriver.elも使ってみるといいです]] 。

同種のものに[[http://emacs.rubikitch.com/ace-jump-mode/][ace-jump-mode(レビュー)]] を使った
[[http://emacs.rubikitch.com/ace-window/][ace-window.el(レビュー)]] があります。
[includeme file="inc-package-install.php" name="switch-window" where="melpa"]

#+end:
** 概要                                                             :noexport:
<2015-02-21 Sat> [[http://emacs.rubikitch.com/win-switch/][win-switch.elの方がもっと使いやすいです。]] 

*switch-window.el* は *C-x o* をカイゼンするものです。

使い方は簡単で、C-x oを *M-x switch-window* に置き換え、
通常通り使うだけです。

2分割のときはそのまま他方のウィンドウに切り替えるのですが、
3分割以上のときはasdf〜とヒント文字がつき、
それを選択することで目的のウィンドウに切り替えます。

とはいえ、3分割以上をしない人とか、
*other-window* をC-tのように1ストロークに割り当てている人は
あまり恩恵を感じないかもしれません。

よくウィンドウを分割する人は [[http://emacs.rubikitch.com/owdriver/][owdriver.elも使ってみるといいです]] 。

同種のものに[[http://emacs.rubikitch.com/ace-jump-mode/][ace-jump-mode(レビュー)]] を使った
[[http://emacs.rubikitch.com/ace-window/][ace-window.el(レビュー)]] があります。

** 設定 [[http://rubikitch.com/f/141215074846.switch-window.el][141215074846.switch-window.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141215/141215074846.switch-window.el"
#+BEGIN_SRC fundamental
(setq switch-window-shortcut-style 'qwerty)
(global-set-key (kbd "C-x o") 'switch-window)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141215074846.switch-window.el
$ emacs -Q -f package-initialize -l 141215074846.switch-window.el
#+END_EXAMPLE
# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141215075328.png
Fig1: 多分割されていても
http://rubikitch.com/f/20141215075650.png
Fig2: ヒント文字でワンタッチ切り替え！

[includeme file="inc-package-relate.php" name="switch-window"]
