#+BLOG: rubikitch
#+POSTID: 673
#+DATE: [2014-12-07 Sun 03:47]
#+PERMALINK: google-translate
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION: M-x google-translate-enja-or-jaenは現在のセンテンス、region、入力文字列、引数を言語自動判別で英訳・和訳します。
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs
#+EL_PKG_NAME: google-translate
#+EL_TAGS: emacs, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, emacs %p スクリーンショット, emacs Google翻訳, emacs 英訳, emacs 和訳, emacs 英語 翻訳, emacs 翻訳 自動判別, 
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+EL_TITLE0: 【設定パワーアップ】Google翻訳で言語自動判別しつつ英訳・和訳する！
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージgoogle-translateの紹介
#+MYTAGS: package:google-translate, emacs 使い方, emacs コマンド, emacs, emacs lisp google-translate, elisp google-translate, emacs melpa google-translate, emacs google-translate 使い方, emacs google-translate 設定, emacs パッケージ google-translate, emacs google-translate スクリーンショット, emacs Google翻訳, emacs 英訳, emacs 和訳, emacs 英語 翻訳, emacs 翻訳 自動判別, 
#+TAGS: package:google-translate, emacs 使い方, emacs コマンド, emacs, emacs lisp google-translate, elisp google-translate, emacs melpa google-translate, emacs google-translate 使い方, emacs google-translate 設定, emacs パッケージ google-translate, emacs google-translate スクリーンショット, emacs Google翻訳, emacs 英訳, emacs 和訳, emacs 英語 翻訳, emacs 翻訳 自動判別, , Emacs, google-translate.el, M-x google-translate-enja-or-jaen, google-translate-translation-directions-alist, M-x google-translate-smooth-translate, google-translate.el, M-x google-translate-enja-or-jaen, google-translate-translation-directions-alist, M-x google-translate-smooth-translate
#+TITLE: emacs google-translate.el : 【設定パワーアップ】Google翻訳で言語自動判別しつつ英訳・和訳する！ | MELPA Emacs Lisp Elisp パッケージ インストール 設定 使い方 スクリーンショット
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>google-translate</td></tr>
<tr><td>概要(原文)</td><td>Emacs interface to Google Translate.</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/atykhonov/google-translate">https://github.com/atykhonov/google-translate</a></td></tr>
<tr><td>バージョン</td><td>20160824.1707</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:google-translate/">package:google-translate</a> </td></tr>
</table>
<br />
#+END_HTML
<2014-12-30 Tue>設定を大幅パワーアップ！！！！

*google-translate.el* は、Google翻訳APIを使って
様々な言語の翻訳を行います。

しかも高速に動作します！

英語に悩んでいる人には朗報ですね。

本設定では、英語・日本語の自動判別をしたコマンドを用意しました。

ASCII文字でのみ構成されている場合は英語とみなします。

C-c tに割り当てた *M-x google-translate-enja-or-jaen* は、
以下の挙動を取ります。

- C-c t (regionあり): regionを翻訳
- C-c t (regionなし): 現在のセンテンスを翻訳(NEW!!)
- C-u C-c t: 入力文字列を翻訳(NEW!!)
- (google-translate-enja-or-jaen "english string"): 英語→日本語
- (google-translate-enja-or-jaen "日本語文字列"): 日本語→英語


もし英語・日本語以外の言語を使うならば、
*google-translate-translation-directions-alist* に
様々な言語を設定し、 *M-x google-translate-smooth-translate* を
直接使いましょう。

** google-translate インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install google-translate


#+end:
** 概要                                                             :noexport:
<2014-12-30 Tue>設定を大幅パワーアップ！！！！

*google-translate.el* は、Google翻訳APIを使って
様々な言語の翻訳を行います。

しかも高速に動作します！

英語に悩んでいる人には朗報ですね。

本設定では、英語・日本語の自動判別をしたコマンドを用意しました。

ASCII文字でのみ構成されている場合は英語とみなします。

C-c tに割り当てた *M-x google-translate-enja-or-jaen* は、
以下の挙動を取ります。

- C-c t (regionあり): regionを翻訳
- C-c t (regionなし): 現在のセンテンスを翻訳(NEW!!)
- C-u C-c t: 入力文字列を翻訳(NEW!!)
- (google-translate-enja-or-jaen "english string"): 英語→日本語
- (google-translate-enja-or-jaen "日本語文字列"): 日本語→英語


もし英語・日本語以外の言語を使うならば、
*google-translate-translation-directions-alist* に
様々な言語を設定し、 *M-x google-translate-smooth-translate* を
直接使いましょう。


** 設定 [[http://rubikitch.com/f/141230072954.google-translate-2.el][141230072954.google-translate-2.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141230/141230072954.google-translate-2.el"
#+BEGIN_SRC fundamental
(require 'google-translate)

(defvar google-translate-english-chars "[:ascii:]"
  "これらの文字が含まれているときは英語とみなす")
(defun google-translate-enja-or-jaen (&optional string)
  "regionか、現在のセンテンスを言語自動判別でGoogle翻訳する。"
  (interactive)
  (setq string
        (cond ((stringp string) string)
              (current-prefix-arg
               (read-string "Google Translate: "))
              ((use-region-p)
               (buffer-substring (region-beginning) (region-end)))
              (t
               (save-excursion
                 (let (s)
                   (forward-char 1)
                   (backward-sentence)
                   (setq s (point))
                   (forward-sentence)
                   (buffer-substring s (point)))))))
  (let* ((asciip (string-match
                  (format "\\`[%s]+\\'" google-translate-english-chars)
                  string)))
    (run-at-time 0.1 nil 'deactivate-mark)
    (google-translate-translate
     (if asciip "en" "ja")
     (if asciip "ja" "en")
     string)))
(global-set-key (kbd "C-c t") 'google-translate-enja-or-jaen)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141230072954.google-translate-2.el
$ emacs -Q -f package-initialize -l 141230072954.google-translate-2.el
#+END_EXAMPLE


# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141207040527.png
Fig1: 翻訳！
