#+BLOG: rubikitch
#+POSTID: 565
#+BLOG: rubikitch
#+DATE: [2014-12-22 Mon 13:52]
#+PERMALINK: dired-subtree
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:diredのサブディレクトリ直下にその内容を挿入する。「i」(dired-maybe-insert-subdir)とは違い、見た目的にスッキリしている
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ファイラ
#+EL_PKG_NAME: dired-subtree
#+TAGS: dired
#+EL_TITLE0: 【<2014-12-30 Tue>更新】 diredがディレクトリツリーエディタに進化！dired-detailsにも対応
#+begin: org2blog
#+TITLE: dired-subtree.el : 【<2014-12-30 Tue>更新】 diredがディレクトリツリーエディタに進化！dired-detailsにも対応
[includeme file="inc-package-table.php" name="dired-subtree" where="melpa"]

#+END:
** dired-subtree インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install dired-subtree


#+end:
dired-detailsもインストールしましょう。

M-x package-install dired-details

** 概要
*dired-subtree.el* は、 *dired* にて
ディレクトリの直下にその内容を挿入します。

<2014-12-30 Tue> 「^」をdired-subtreeに対応させました。

標準の「i」(*dired-maybe-insert-subdir*)は
diredバッファの最後尾に挿入しますが、
dired-subtree.elを使えばディレクトリの直下に挿入されます。

つまり、ディレクトリツリーらしく表示されるわけです。

たったこれだけの違いですが、表示が直観的になってわかりやすくなります。

最新版では[[http://emacs.rubikitch.com/dired-details/][dired-details.el(レビュー記事)]] に対応したので、
本設定ではdired-details.elの設定もしておきます。

また、dired-subtreeによって表示させたサブディレクトリに対して
*wdired* を使うこともできます。

なお、同じ機能を持つEmacs 24.4標準の *dired-hide-details-mode* には
まだ対応していません。

作者がまだ24.3を使っているので対応が待たれるところです。


[includeme file="inc-package-install.php" name="dired-subtree" where="melpa"]
** 設定 [[http://rubikitch.com/f/141222134234.dired-subtree.1.el][141222134234.dired-subtree.1.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/141222/141222134234.dired-subtree.1.el"
#+BEGIN_SRC fundamental
(require 'dired-subtree)
;;; iを置き換え
(define-key dired-mode-map (kbd "i") 'dired-subtree-insert)
;;; org-modeのようにTABで折り畳む
(define-key dired-mode-map (kbd "<tab>") 'dired-subtree-remove)
;;; C-x n nでsubtreeにナローイング
(define-key dired-mode-map (kbd "C-x n n") 'dired-subtree-narrow)

;;; ファイル名以外の情報を(と)で隠したり表示したり
(require 'dired-details)
(dired-details-install)
(setq dired-details-hidden-string "")
(setq dired-details-hide-link-targets nil)
(setq dired-details-initially-hide nil)

;;; dired-subtreeをdired-detailsに対応させる
(defun dired-subtree-after-insert-hook--dired-details ()
  (dired-details-delete-overlays)
  (dired-details-activate))
(add-hook 'dired-subtree-after-insert-hook
          'dired-subtree-after-insert-hook--dired-details)

;; find-dired対応
(defadvice find-dired-sentinel (after dired-details (proc state) activate)
  (ignore-errors
    (with-current-buffer (process-buffer proc)
      (dired-details-activate))))
;; (progn (ad-disable-advice 'find-dired-sentinel 'after 'dired-details) (ad-update 'find-dired-sentinel))

;;; [2014-12-30 Tue]^をdired-subtreeに対応させる
(defun dired-subtree-up-dwim (&optional arg)
  "subtreeの親ディレクトリに移動。そうでなければ親ディレクトリを開く(^の挙動)。"
  (interactive "p")
  (or (dired-subtree-up arg)
      (dired-up-directory)))
(define-key dired-mode-map (kbd "^") 'dired-subtree-up-dwim)


#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/141222134234.dired-subtree.1.el
$ emacs -Q -f package-initialize -l 141222134234.dired-subtree.1.el
#+END_EXAMPLE

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
http://rubikitch.com/f/20141222140153.png
Fig1: ディレクトリ直下に表示！

http://rubikitch.com/f/20141222140204.png
Fig2: 「(」を押して詳細を隠したところ

[includeme file="inc-package-relate.php" name="dired-subtree"]
