#+BLOG: rubikitch
#+POSTID: 694
#+BLOG: rubikitch
#+DATE: [2015-02-11 Wed 07:43]
#+PERMALINK: unify-opening
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ファイル関連付け
#+EL_PKG_NAME: unify-opening
#+TAGS: helm, org, ソース解読推奨, dired
#+EL_TITLE0: 【アプリケーション関連付け】org-mode,helm,mu4eでのファイルの開き方をdiredに統一する！
#+EL_URL: 
#+begin: org2blog
#+TITLE: unify-opening.el : 【アプリケーション関連付け】org-mode,helm,mu4eでのファイルの開き方をdiredに統一する！
[includeme file="inc-package-table.php" name="unify-opening" where="melpa"]

#+end:
** 概要
特定のファイルに対してはEmacsではなくて
外部アプリケーションを使いたいことはよくあります。

たとえば、org-modeでの file: のリンクを開き方は
*org-file-apps* という変数で設定します。

たとえば、画像ファイルをxzgvという画像ビューワで開きたいのなら、
#+BEGIN_SRC emacs-lisp :results silent
(add-to-list 'org-file-apps '("bmp$" . "xzgv %s"))
(add-to-list 'org-file-apps '("png$" . "xzgv %s"))
(add-to-list 'org-file-apps '("jpe?g$" . "xzgv %s"))
#+END_SRC
というエントリを加えます。

一方、diredで「!」を実行したときのデフォルトのアプリケーションは
*dired-guess-shell-alist-default* と
*dired-guess-shell-alist-user* で決定されます。

helmで「Open file with default tool」というアクションを
実行するときに使うアプリケーションは
*helm-external-programs-associations* で設定します。

このように、パッケージごとに同じような設定をする必要があるのは無駄です。

そこで *unify-opening.el* はorg-modeとhelmとmu4e(メーラ)
で使う外部アプリケーションをdiredのものに統一します。

つまり、dired-guess-shell-alist-*を使うということです。

unify-opening.elはrequireしただけで挙動が変更される設定集です。

diredで使うアプリケーションといえば[[http://emacs.rubikitch.com/runner-3/][runner.el(レビュー)]]
がありますが、これと併用することをおすすめします。

runner.elで設定してしまえば、それが使われます。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-install.php" name="unify-opening" where="melpa"]
** 設定 [[http://rubikitch.com/f/150211080449.unify-opening.el][150211080449.unify-opening.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/150211/150211080449.unify-opening.el"
#+BEGIN_SRC fundamental
;;; 画像ファイルをemacsではなくて外部アプリケーションで開く場合はこの設定が必要
(require 'cl-lib)
(setq auto-mode-alist
      (cl-delete-if (lambda (x) (equal (cdr x) 'image-mode))
                    auto-mode-alist))

(require 'runner nil t)                ;インストールされているなら使う
(require 'unify-opening)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/150211080449.unify-opening.el
$ emacs -Q -f package-initialize -l 150211080449.unify-opening.el
#+END_EXAMPLE
[includeme file="inc-package-relate.php" name="unify-opening"]
