#+BLOG: rubikitch
#+POSTID: 69
#+BLOG: rubikitch
#+DATE: [2015-02-13 Fri 07:17]
#+PERMALINK: melmag168
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ 
#+DESCRIPTION: 『Emacsの鬼るびきちのココだけの話#168』の予告
#+MYTAGS: 
#+TITLE: あなたの願いを叶える科学的な方法です
#+begin: org2blog-tags

#+end:

今回のメルマガは、本「るびきち塾」の入塾者特典の
『org習慣仕事術』の最後のピースに当たります。

org習慣仕事術とは、僕が脳科学や心理学に精通した人から
大金と何年もの時間をかけて学び取った方法を
Emacsユーザ向けに最適化した仕事術です。

org-modeを使って自分の行動をコントロールし、
次にとるべき行動を明確にし、自動的に習慣化します。

その結果、迷うことがなくなり、
毎日100%行動できるようになります。

迷いややる気のない状態から解放され、
「行動できない病」から未来永劫おさらばできます。

人生、なんでもそうですが、
何かの結果が欲しければ行動しなければなりません。

それも習慣化によって行動し続ける必要があります。

しかし多くの人は何らかの理由をつけて行動できないでいます。

セミナーに出ても実際に行動している人は
10%とか5%と言われています。

ましてや行動し続けている人は1%らしいです。

当然、結果はついてきませんし、
みすみす大金をドブに捨ててます。

「この世の成功者はほんの数%」と言われているのは、
行動し続けられないことが最大の原因です。

org習慣仕事術を朝一番に稼動させてしまえば、
自動的に行動できるようになり、
あっさりと習慣化できてしまいます。

org習慣仕事術のスイッチを入れた瞬間、
もはや行動することから逃れられなくなります！！

行動しないという選択肢が消え失せます。

そう考えると「100%習慣化できる方法」というのは
とてつもない価値があると思いませんか？

「Emacsが行動を促してくれるから余計燃える！」
という実践者からの声もいただきました。

org習慣仕事術はanything.elが霞むほどの僕の秘奥義です。

入塾者には最大の感謝と敬意を表し、
org習慣仕事術を特典で付けているのですが、
今回はそれと日記を組み合わせます。

日記の多くのメリットは先週語ったのですが、
org習慣仕事術との相乗効果で
効果は数倍数十倍に膨れ上がります。

なぜなら、org習慣仕事術で記録されたclock情報を日記で振り返ることで、
時間の使い方が分かり、今日学んだ教訓を書き留められるからです。

賢い人とは、あらゆる物事から教訓を学び取る人のことです。

org習慣仕事術＋日記で同じ過ちを繰り返すことがなくなり、
あなたの人生は間違いなく進化します。

教訓を得ないと、また同じような痛い目に遭いますが、
教訓を得ればそれを回避できます。

今回のメルマガという小さなきっかけによって、
数年後のあなたは、驚くほど成長していることでしょう。

なぜそう言えるかというと、僕自身が実践している中で
進化を実感しているからです。

もし、入塾者で「org習慣仕事術受け取ってないよ」という方がいましたら、
「org習慣仕事術申請」とメルマガに返信してください。

org習慣仕事術が欲しい方はこちらへ
↓
http://rubikitch.com/juku/

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
