#+BLOG: rubikitch
#+POSTID: 731
#+BLOG: rubikitch
#+DATE: [2015-03-01 Sun 07:43]
#+PERMALINK: clipmon
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: コピー・貼り付け
#+EL_PKG_NAME: clipmon
#+TAGS: メモ
#+EL_TITLE0: 【メモ革命】任意のブラウザからクリップボード経由でガンガンメモれ！！
#+EL_URL: 
#+begin: org2blog
#+TITLE: clipmon.el : 【メモ革命】任意のブラウザからクリップボード経由でガンガンメモれ！！
[includeme file="inc-package-table.php" name="clipmon" where="melpa"]

#+end:
** 概要
これはすごい！

Emacsでメモをとる方法は従来ならば *M-x org-capture* や
*ChangeLogメモ* などの方法があります。

しかし、これらの方法だとEmacsに閉じているため、
Emacs以外のアプリケーションから直接メモすることができません。

時代の流れにより、今やEmacsだけですべてをまかなえなくなっています。

Emacsに代わってWebブラウザこそが統合環境の王者なのが現状です。

Webサイトを見ているとメモを取りたくなることが多々ありますが、
Emacsでやるには[[http://rubikitch.com/category/eww/][Emacs内蔵WebブラウザEWW(カテゴリ)]] や *emacs-w3m* などの
窮屈な方法に頼らざるを得ません。

今(Emacs外の)Webブラウザで見ているサイトから直接メモを取るには
クリップボードを経由するしかありません。

しかし、それではクリップボードに保存して
そこからC-yでEmacsに貼り付ける必要があり
手間がかかってしまいます。

そこで *M-x clipmon-autoinsert-toggle* コマンドを使いましょう。

このコマンドはクリップボードが更新されるたびに、
カレントバッファにその内容が貼り付けられます。

よって、Webブラウザからメモを取るためには
*M-x org-capture* などでメモ用のバッファを開き
*M-x clipmon-autoinsert-toggle* を実行し、
ブラウザに切り替えて、マウスで範囲選択するだけです。

あとはブラウザ内で何度でも範囲選択すれば
その内容が次々とEmacsに貼り付けられるので
Emacsに戻ることなく、ガンガンメモできます。

OSのクリップボードを経由するので、
ブラウザは *Firefox* 、 *Chrome* などなんでも構いません。

それどころかブラウザ以外の任意のアプリケーションで使えます。

一度体験してみてください。

/目から鱗です！！/
[includeme file="inc-package-install.php" name="clipmon" where="melpa"]
** 音でお知らせ
*M-x clipmon-autoinsert-toggle* を実行したときと、
クリップボードの内容を貼り付けたときには音でお知らせしてくれます。

しかし、サウンド機能を無効でEmacsをコンパイルしたときには
#+BEGIN_EXAMPLE
This Emacs binary lacks sound support
#+END_EXAMPLE
というエラーが出て *clipmon.el* が使えません。

そのときは [[http://emacs.rubikitch.com/play-sound/][この記事の設定で]] 外部プレイヤーを使うようにしてください。

OSのパッケージからインストールした場合は問題ありません。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-relate.php" name="clipmon"]
