#+BLOG: rubikitch
#+POSTID: 741
#+BLOG: rubikitch
#+DATE: [2015-03-06 Fri 05:09]
#+PERMALINK: yatemplate
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: 入力支援
#+EL_PKG_NAME: yatemplate
#+TAGS: yasnippet
#+EL_TITLE0: 【新規ファイル作成支援】auto-insertのテンプレートをyasnippetに進化させる
#+EL_URL: 
#+begin: org2blog
#+TITLE: yatemplate.el : 【新規ファイル作成支援】auto-insertのテンプレートをyasnippetに進化させる
[includeme file="inc-package-table.php" name="yatemplate" where="melpa"]

#+end:
** 概要

*auto-insert-mode* は新規ファイル作成時に
決まった内容のテンプレートを用意したり、
特定の関数を実行できたりします。

一方で *yasnippet.el* はいまや鉄板の強力テンプレートです。

しかし、yasnippet.el登場後8年くらいたつにもかかわらず
なぜか両者を組み合わせる機能がないです。

*yatemplate.el* を使えば、auto-insertのテンプレートをyasnippetにできます。

使い方は簡単で、 ~/.emacs.d/templates/ 以下に
決められたファイル名でyasnippetファイルを配置するだけです。

ファイル名は1つのコロンで区切られていて、
「番号:正規表現」と指定します。

番号は *auto-insert-alist* へ追加する順序を指定するために必要です。

たとえば
- ~/.emacs.d/templates/00:test_.*.py
- ~/.emacs.d/templates/01:.*.py
というyatemplateファイルがあったとき、
test_*.py の方が優先されます。


開発して日が浅いため(2/28から)まだ荒削りなので設定で対処しています。
- yatemplateファイルを *snippet-mode* にする
- yatemplateファイル追加時に即 *auto-insert-alist* に反映させる

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-install.php" name="yatemplate" where="melpa"]
** 設定 [[http://rubikitch.com/f/150306045100.yatemplate.el][150306045100.yatemplate.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/150306/150306045100.yatemplate.el"
#+BEGIN_SRC fundamental
(yatemplate-fill-alist)
(auto-insert-mode 1)
(defun find-file-hook--yatemplate ()
  "yatemplateのsnippetのテストができるようにするためにsnippet-modeにする"
  (when (string-match "emacs.*/templates/" buffer-file-name)
    (let ((mode major-mode))
      (snippet-mode)
      (setq-local yas--guessed-modes (list mode)))))
(add-hook 'find-file-hook 'find-file-hook--yatemplate)
(defun after-save-hook--yatemplate ()
  "yatemplateファイル保存後、auto-insert-alistに反映させる"
  (when (string-match "emacs.*/templates/" buffer-file-name)
    (yatemplate-fill-alist)))
(add-hook 'after-save-hook 'after-save-hook--yatemplate)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/150306045100.yatemplate.el
$ emacs -Q -f package-initialize -l 150306045100.yatemplate.el
#+END_EXAMPLE
[includeme file="inc-package-relate.php" name="yatemplate"]
