#+BLOG: rubikitch
#+POSTID: 889
#+BLOG: rubikitch
#+DATE: [2015-05-04 Mon 04:57]
#+PERMALINK: easy-repeat
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: キーバインド
#+EL_PKG_NAME: easy-repeat
#+TAGS: 
#+EL_TITLE0: 【簡易smartrep/hydra】最後のキーで直前のコマンドを繰り返し実行させる
#+EL_URL: 
#+begin: org2blog
#+TITLE: easy-repeat.el : 【簡易smartrep/hydra】最後のキーで直前のコマンドを繰り返し実行させる
[includeme file="inc-package-table.php" name="easy-repeat" where="melpa"]

#+end:
** 概要
<2015-05-02 Sat> に登録された新入りです。

たとえば、複数のウィンドウに分割されている状態で
C-x oを連続してウィンドウを選択するのは面倒です。

この問題に対処するために
[[http://emacs.rubikitch.com/ace-window/][ace-window.el(レビュー)]] とか
[[http://emacs.rubikitch.com/switch-window/][switch-window.el(レビュー)]] とか
もっと強力な[[http://emacs.rubikitch.com/win-switch/][win-switch.el(レビュー)]] などがあります。

[[http://emacs.rubikitch.com/hydra/][smartrep.elやhydra.el(比較レビュー)]] を使えば
プレフィクスキーを省略できるようになり、
C-x o o ...と操作できるようになります。

この *easy-repeat.el* は、smartrep/hydraよりもシンプルで、
指定されたコマンドの最後のキーで繰り返せるようにしています。

C-x oの後にoを押せば *other-window* を繰り返せます。

smartrep/hydraではo以外にも他のキーでも
プレフィクスキーを省略できるようになります。

機能的には縮小版ですが、コードはわずか40行です！

そのうち中核をなす部分は10行少々です。
[includeme file="inc-package-install.php" name="easy-repeat" where="melpa"]
** メカニズム
#+BEGIN_SRC emacs-lisp :results silent
(defun easy-repeat--repeat (orig-fun &rest args)
  (apply orig-fun args)
  (when (called-interactively-p 'interactive)
    (set-transient-map
     (let ((map (make-sparse-keymap)))
       (define-key map (vector last-command-event) #'repeat)
       map))))

(defun easy-repeat--add ()
  (dolist (command easy-repeat-command-list)
    (advice-add command :around #'easy-repeat--repeat)))

(defun easy-repeat--remove ()
  (dolist (command easy-repeat-command-list)
    (advice-remove command #'easy-repeat--repeat)))
#+END_SRC

これらの部分を読んでみればわかるように
*easy-repeat-command-list* でリピート対象のコマンド各々に対して
[[http://emacs.rubikitch.com/nadvice/][Emacs 24.4で追加されたnadvice.el]] によるアドバイスがかけられています。

で、 *set-transient-map* 関数で一度きりのキーマップにて
*repeat* コマンド(C-x z)を指定しています。

この関数は *set-temporary-overlay-map* という名前でEmacs 24.3で導入され、
Emacs 24.4でset-transient-mapという名前に変更された新機能です。

この関数を使うことでrepeatや *C-x C-i(indent-rigidly)* や
*C-x e(kmacro-end-or-call-macro)* や
*C-x C--(text-scale-adjust)* などが
smartrep風味にプレフィクスキーを省略できるようになっています。

実におもしろい新機能ですね。


# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-relate.php" name="easy-repeat"]
