#+BLOG: rubikitch
#+POSTID: 930
#+BLOG: rubikitch
#+DATE: [2015-05-25 Mon 07:31]
#+PERMALINK: gnupack-1302
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: リリース情報
#+DESCRIPTION: 
#+TITLE: 【gnupack 13.02リリース】バグフィクスリリース
#+begin: org2blog-tags
# content-length: 1223

#+end:
http://d.hatena.ne.jp/ksugita0510/20150524/p1

展開するだけで簡単にCygwin 2.0.2＆Emacs 24.5が使える
gnupackですが、13.02にバージョンアップしました。

全体的にバグフィクスが中心です。

#+BEGIN_QUOTE
- ユーザ名設定に関する改修

  ドメイン環境において、ユーザ名が「<ドメイン名＋ユーザ名>」になる問題に対し改修しました。実装の詳細は /app/script/{mkpasswd.pl,mkgroup.pl}を参照ください。
- cygwinのシンボリックリンク設定を見直し

  cygwinで作成したシンボリックリンクをWindowsアプリからも利用できるように設定を見直しました。具体的には、「winsymlinks:native」を設定しています（本件は、掲示板のCYGWINに設定しているnowinsymlinksについてで報告いただいた件です）
- emacsの機種依存文字向けの設定を追加

  cp932の機種依存文字が正しく表示できなかった問題を改修しました。（本件は、掲示板のCP932で書かれたファイルの文字化けについてで報告いただいた件です）
- tmpディレクトリが作成されない問題を改修

  /tmpディレクトリの実体となるディレクトリが存在しない場合に、ディレクトリ作成がされず、エラーが表示される問題を改修しました。

- minttyとemacsの antialias設定を有効にしてみました。

- コンテキストメニュー（右クリックメニュー）に起動プログラムを登録するための、vbsスクリプトをお試しでバンドルしました。ファイルのコンテキストメニューに対して emacs起動プログラム、フォルダのコンテキストメニューに対し emacs起動プログラムとcygwin起動プログラムを追加します
#+END_QUOTE

ユーザ名については、Emacs起動時に
#+BEGIN_EXAMPLE
Error (initialization): User <username> has no home directory
#+END_EXAMPLE
のようなエラーが出ることがありましたが、
[[http://hardsoft.at.webry.info/201505/article_4.html][/etc/passwd]]にまつわるCygwin2.0.2の問題らしいです。

CP932(Shift_JIS)で書かれたファイルが文字化けしていましたが、解消されました。

この御時世にもこんな昔からの問題に悩まされるのはちょっとアレですけどね。



# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
