#+BLOG: rubikitch
#+POSTID: 1122
#+BLOG: rubikitch
#+DATE: [2015-09-06 Sun 10:27]
#+PERMALINK: kill-or-bury-alive
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: バッファ切り替え
#+EL_PKG_NAME: kill-or-bury-alive
#+TAGS: 
#+EL_TITLE0: バッファは殺すよりも生き埋めにしよう
#+EL_URL: 
#+begin: org2blog
#+TITLE: kill-or-bury-alive.el : バッファは殺すよりも生き埋めにしよう
[includeme file="inc-package-table.php" name="kill-or-bury-alive" where="melpa"]

#+end:
** 概要
今見ているバッファを視界から消すには、
普通ならばC-x kでバッファを削除しますよね。

しかし、現在のコンピュータは大量のメモリを積んでいます。

将来、わずかながらでも再びそのバッファを見る可能性があることを考えると、
バッファを削除するのは馬鹿馬鹿しくなってきます。

そこで、C-x kに *M-x bury-buffer* を割り当てている人もいます。

bury-bufferは、バッファを削除するのではなく、
バッファリストの最後尾に移動するコマンドです。

そうすることでバッファ選択の選択肢に登りにくくなります。

いわば生き埋めにするような状態です。

とはいえ、すべてのバッファを生き埋めにするのではなく、
本当に削除したいバッファを指定したくなるときもあります。

そこで *kill-or-bury-alive.el* の出番です。

*M-x kill-or-bury-alive* をC-x kに割り当て直せば、
普段はbury-bufferを使用し、C-uをつければ削除します。

M-x kill-or-bury-aliveを制御する重要な変数は
*kill-or-bury-alive-must-die-list* で、
削除するバッファの正規表現、またはメジャーモードを指定します。

バッファがあまりにも増えすぎてしまった場合はどうします？
素直にEmacsを再起動してください。



# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-install.php" name="kill-or-bury-alive" where="melpa"]
** 設定 [[http://rubikitch.com/f/150906103640.kill-or-bury-alive.el][150906103640.kill-or-bury-alive.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/150906/150906103640.kill-or-bury-alive.el"
#+BEGIN_SRC fundamental
(global-set-key (kbd "C-x k") 'kill-or-bury-alive)
(setq kill-or-bury-alive-must-die-list
      '("\\.\\(jpg\\|png\\|gif\\|bmp\\)$" ;画像は削除する
        ;; shellやeshellのバッファは削除する
        shell-mode eshell-mode
        ))
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/150906103640.kill-or-bury-alive.el
$ emacs -Q -f package-initialize -l 150906103640.kill-or-bury-alive.el
#+END_EXAMPLE
[includeme file="inc-package-relate.php" name="kill-or-bury-alive"]
