#+BLOG: rubikitch
#+POSTID: 1183
#+BLOG: rubikitch
#+DATE: [2015-10-08 Thu 07:43]
#+PERMALINK: sync-recentf
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ファイルを開く
#+EL_PKG_NAME: sync-recentf
#+TAGS: recentf
#+EL_TITLE0: recentf(最近開いたファイル)を複数のEmacs間で同期させる
#+EL_URL: 
#+begin: org2blog
#+TITLE: sync-recentf.el : recentf(最近開いたファイル)を複数のEmacs間で同期させる
[includeme file="inc-package-table.php" name="sync-recentf" where="melpa"]

#+end:
** 概要
複数のEmacsを同時に立ち上げていると、
最近開いたファイルが上書きされてしまう恐れがあります。

なぜなら、最近開いたファイルは変数 *recentf-list* に記憶されており、
その内容が変数 *recentf-save-file* が示すファイル(~/.emacs.d/recentf) に
記憶されるからです。

複数のEmacsがそのファイルを取り合いすると、上書きされてしまうのです。

これは僕自身も体験したことであり、この事故により
貴重な最近開いたファイルの情報が失われてしまいました。

recentfを含むパッケージの動作確認をしているときに、
その事故は起きました。

この事故を防ぐには2つの方法があります

1つはメインで使うEmacsの recentf-save-file を別なファイルにすることで、
僕自身がやっている方法です。

僕のように1つのEmacsインスタンスを使い回す人はこれでいいのですが、
常に複数のEmacsを立ち上げている人は別のアプローチが必要です。

それは、 *sync-recentf.el* を使って複数のEmacs間の
recentf-list を同期させることです。

最近開いたファイルは *recentf-save-list* によってファイルに書き出されますが、
sync-recentf.el はファイル書き出し前に同期処理を加えるよう挙動を変更します。

同期は recentf-save-file に保存された内容を読み込み、
前回の同期時から追加されたファイルを加えて recentf-save-file に
書き出すことで行います。

また、 *recentf-cleanup* にも同期処理を行うようアドバイスがかけられており、
*recentf-auto-cleanup* を設定することで一定時間おきに同期されることになります。

最近開いたファイルに限らず、複数のEmacsインスタンスで
ファイルの取り合いになるときにどのように解決しているのかを
見ていくのはおもしろいのではないでしょうか。


# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-install.php" name="sync-recentf" where="melpa"]
** 設定 [[http://rubikitch.com/f/151008073113.sync-recentf.el][151008073113.sync-recentf.el(以下のコードと同一)]]
#+BEGIN: include :file "/r/sync/junk/151008/151008073113.sync-recentf.el"
#+BEGIN_SRC fundamental
(require 'sync-recentf)
(setq recentf-auto-cleanup 60)
(recentf-mode 1)
#+END_SRC

#+END:

** 実行方法
#+BEGIN_EXAMPLE
$ wget http://rubikitch.com/f/151008073113.sync-recentf.el
$ emacs -Q -f package-initialize -l 151008073113.sync-recentf.el
#+END_EXAMPLE
[includeme file="inc-package-relate.php" name="sync-recentf"]
