#+BLOG: rubikitch
#+POSTID: 2502
#+DATE: [2016-07-23 Sat 08:09]
#+PERMALINK: sudo-edit
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: Emacs, ソース解読推奨, 
#+EL_PKG_NAME: sudo-edit
#+EL_TAGS: emacs, %p, %p.el, emacs lisp %p, elisp %p, emacs %f %p, emacs %p 使い方, emacs %p 設定, emacs パッケージ %p, relate:tramp, relate:sudo-ext, relate:crux, sudoedit emacs, sudo emacs, ファイルをrootで開く, システムファイルを編集する, root権限でファイルを編集する, root, sudo
#+EL_TITLE: Emacs Lisp Elisp パッケージ インストール  使い方 
#+EL_TITLE0: ★MELPA最短行数★rootでファイルを開く・カレントバッファを開き直す
#+EL_URL: 
#+begin: org2blog
#+DESCRIPTION: MELPAのEmacs Lispパッケージsudo-editの紹介
#+MYTAGS: package:sudo-edit, emacs 使い方, emacs コマンド, emacs, sudo-edit, sudo-edit.el, emacs lisp sudo-edit, elisp sudo-edit, emacs melpa sudo-edit, emacs sudo-edit 使い方, emacs sudo-edit 設定, emacs パッケージ sudo-edit, relate:tramp, relate:sudo-ext, relate:crux, sudoedit emacs, sudo emacs, ファイルをrootで開く, システムファイルを編集する, root権限でファイルを編集する, root, sudo
#+TAGS: package:sudo-edit, emacs 使い方, emacs コマンド, emacs, sudo-edit, sudo-edit.el, emacs lisp sudo-edit, elisp sudo-edit, emacs melpa sudo-edit, emacs sudo-edit 使い方, emacs sudo-edit 設定, emacs パッケージ sudo-edit, relate:tramp, relate:sudo-ext, relate:crux, sudoedit emacs, sudo emacs, ファイルをrootで開く, システムファイルを編集する, root権限でファイルを編集する, root, sudo, Emacs, ソース解読推奨, , M-x sudo-edit, M-x sudo-edit-current-file, M-x sudo-edit, M-x sudo-edit-current-file
#+TITLE: emacs sudo-edit.el : ★MELPA最短行数★rootでファイルを開く・カレントバッファを開き直す | MELPA Emacs Lisp Elisp パッケージ インストール  使い方 
#+BEGIN_HTML
<table>
<tr><td>パッケージ名</td><td>sudo-edit</td></tr>
<tr><td>概要(原文)</td><td>Utilities for opening files with sudo</td></tr>
<tr><td>リポジトリ</td><td><a href="http://melpa.org/">MELPA</a></td></tr>
<tr><td>取得先</td><td><a href="https://github.com/nflath/sudo-edit">https://github.com/nflath/sudo-edit</a></td></tr>
<tr><td>バージョン</td><td>20160627.1203</td></tr>
<tr><td>関連記事</td><td><a href="http://rubikitch.com/tag/package:sudo-edit/">package:sudo-edit</a> <a href="http://rubikitch.com/tag/package:tramp/">package:tramp</a> <a href="http://rubikitch.com/tag/package:sudo-ext/">package:sudo-ext</a> <a href="http://rubikitch.com/tag/package:crux/">package:crux</a></td></tr>
</table>
<br />
#+END_HTML

sudo-edit.elはカレントバッファ・任意のファイルを
root権限で開き直すコマンドを2つ提供しています。

*M-x sudo-edit* はファイルをroot権限で開きます。
システムファイルを編集するときに便利です。
なお、C-u M-x sudo-editでカレントバッファをrootで開き直します。

*M-x sudo-edit-current-file* は現在位置を保持したまま
カレントバッファをrootで開き直します。

たった6行のコマンドを2つだけ定義しているので、
[[http://rubikitch.com/2016/07/07/readable-small-packages/][おそらくMELPAで登録されているパッケージで最短行数]] でしょう。
このように短いパッケージでもMELPAに登録されるので、
自分用のコマンドで他人にとっても便利だと感じたならば
思い切って[[http://syohex.hatenablog.com/entry/20121021/1350823391][MELPAに登録申請]] すればいいです。
これがEmacs界全体への貢献となります。

この記事から新たなカテゴリ「[[http://rubikitch.com/category/%25e3%2582%25bd%25e3%2583%25bc%25e3%2582%25b9%25e8%25a7%25a3%25e8%25aa%25ad%25e6%258e%25a8%25e5%25a5%25a8/][ソース解読推奨]] 」を作成しました。
Emacsを深く理解したい方、elispを学びたい方が読めば
勉強になると判断したパッケージをこのカテゴリに入れます。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
** sudo-edit インストール
このパッケージはmelpaにあるので [[http://rubikitch.com/package-initialize][パッケージの初期設定]] を行ってください。

M-x package-refresh-contents
M-x package-install sudo-edit


#+end:
** 概要                                                             :noexport:

sudo-edit.elはカレントバッファ・任意のファイルを
root権限で開き直すコマンドを2つ提供しています。

*M-x sudo-edit* はファイルをroot権限で開きます。
システムファイルを編集するときに便利です。
なお、C-u M-x sudo-editでカレントバッファをrootで開き直します。

*M-x sudo-edit-current-file* は現在位置を保持したまま
カレントバッファをrootで開き直します。

たった6行のコマンドを2つだけ定義しているので、
[[http://rubikitch.com/2016/07/07/readable-small-packages/][おそらくMELPAで登録されているパッケージで最短行数]] でしょう。
このように短いパッケージでもMELPAに登録されるので、
自分用のコマンドで他人にとっても便利だと感じたならば
思い切って[[http://syohex.hatenablog.com/entry/20121021/1350823391][MELPAに登録申請]] すればいいです。
これがEmacs界全体への貢献となります。

この記事から新たなカテゴリ「[[http://rubikitch.com/category/%25e3%2582%25bd%25e3%2583%25bc%25e3%2582%25b9%25e8%25a7%25a3%25e8%25aa%25ad%25e6%258e%25a8%25e5%25a5%25a8/][ソース解読推奨]] 」を作成しました。
Emacsを深く理解したい方、elispを学びたい方が読めば
勉強になると判断したパッケージをこのカテゴリに入れます。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
