#+BLOG: rubikitch
#+POSTID: 1550
#+BLOG: rubikitch
#+DATE: [2016-08-27 Sa 12:24]
#+PERMALINK: kill-emacs
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: カスタマイズ
#+DESCRIPTION: 
#+TITLE: うっかりEmacsを終了することを二度となくす超簡単な方法
#+TAGS: るびきちオススメ
#+begin: org2blog-tags
# content-length: 1078

#+end:
http://nagayasu-shinya.seesaa.net/article/emacs-confirm-kill-emacs.html

#+BEGIN_QUOTE
ご存知の通りEmacs のファイル保存のコマンドはC-x C-s です。また、終了コマンドは C-x C-c です。このせいで、Emacs使いなら一度は経験があるのではと思うミスが「ファイルを保存しようとしたらうっかりEmacsを終了してしまった」というやつです。キーボードのxとsとcが近すぎるゆえに起こる不幸……C-x C-s とタイプしたつもりが C-x C-c とタイプミスしてしまうというかなしい事故。

変更をしたけど未保存状態のファイルがある場合は Emacs が「本当に終了してええの？変更した未保存のファイルあるけど？」と聞いてくれますが、それがない場合はそのまま終了してしまいます。scratch バッファを使っている場合なども無慈悲に終了してしまい、泣きそうになります。
#+END_QUOTE

るびきち塾塾生の永安さんの人気ページからです。

僕はもうひとつの方法を提案します。

ここであなたに質問です。

そもそもEmacsを終了することって多いですか？
基本的に一度立ち上げたらずっとひきこもって使うのがEmacsではないでしょうか。

そもそもめったにEmacsを終了しないのであれば
C-x C-cのキー割り当てを外してしまうことを提案します。

C-x C-cは *save-buffers-kill-emacs* という長いコマンドですので、
いざ終了するときにM-x save-buffers-kill-emacsと打ち込むのは面倒ですよね。

それならばM-x exitで終了できるように別名をつけてあげると、終了するときは楽です。

C-x C-cには別なコマンドを割り当てれば幸せになれます。

#+BEGIN_SRC emacs-lisp :results silent
(global-unset-key (kbd "C-x C-c"))
(defalias 'exit 'save-buffers-kill-emacs)
;;; なんでもいいよ
;; (global-set-key (kbd "C-x C-c") 'some-command)
#+END_SRC


# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
