#+BLOG: rubikitch
#+POSTID: 1504
#+BLOG: rubikitch
#+DATE: [2016-08-01 Mon 08:44]
#+PERMALINK: crux-buffer-file-window
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: ファイルを開く
#+EL_PKG_NAME: crux
#+TAGS: ソース解読推奨, crux
#+EL_TITLE0: バッファ・ファイル操作を超便利にするコマンド10選！
#+EL_URL: 
#+begin: org2blog
#+TITLE: crux.el : バッファ・ファイル操作を超便利にするコマンド10選！
[includeme file="inc-package-table.php" name="crux" where="melpa"]

#+end:
** 概要
#+INCLUDE: "include.crux.org" 

cruxには標準にありそうで実はない便利なコマンドがたくさん用意されています。
ここではバッファ・ファイル操作に関する10個のコマンドたちです。
ちょうど、かゆいところに手が届くコマンドたちです。


[includeme file="inc-package-install.php" name="crux" where="melpa"]
** M-x crux-rename-file-and-buffer
このコマンドはバッファ名とそれに関連づけられているファイル名を同時にリネームします。
VCにも対応しているのでバージョン管理システムでもリネームします。
自分でも定義していますが、このコマンドは非常に便利です。

標準でもdiredからならばファイル名とバッファ名の同時リネームが可能なのですがね…

*M-x crux-rename-buffer-and-file* というエイリアスも定義されています。

** M-x crux-delete-file-and-buffer
このコマンドはバッファを削除するのと同時に関連づけられているファイルも削除します。
VCにも対応しているのでバージョン管理システムからも削除します。

標準でもdiredからならば同時削除が可能です。

*M-x crux-delete-buffer-and-file* というエイリアスも定義されています。

** M-x crux-recentf-find-file
このコマンドは最近使ったファイルからファイルを選択して開けます。
helm-modeを有効にすればhelmからでも開けますが、M-x helm-recentfがありますからねぇ…

** M-x crux-switch-to-previous-buffer
このコマンドは直前に切替えたバッファに切替えます。
続けて実行すれば、元のバッファに戻ります。

** M-x crux-kill-other-buffers
このコマンドはカレントバッファ以外のファイルバッファを削除します。
ん〜、これを使うくらいなら普通に再起動しますね、僕なら。

** M-x crux-create-scratch-buffer
このコマンドは新しく*scratch*バッファを作成します。
他にも*scratch*バッファを永続するパッケージをちらほら見かけますが、
保存ができないという最大の欠点をはらんでいます。

僕ならば試行錯誤用の新規ファイルを開く拙作open-junk-fileパッケージを何年も使い続けています。

** M-x crux-view-url
このコマンドはURL(カーソル位置ならばそれを使う)のソースを表示します。
しかし、日本語が表示できないのでは正直使いものにならないです。

** M-x crux-transpose-windows
このコマンドは2つのウィンドウのバッファを入れ替えます。
*M-x crux-swap-windows* というエイリアスが定義されています。

** M-x crux-find-user-init-file
このコマンドはinit.elを別ウィンドウで開きます。
init.elをしょっちゅういじる人にはキーに割り当てておくと便利でしょう。

** M-x crux-find-shell-init-file
このコマンドは使っているシェルの初期化ファイルを別ウィンドウで開きます。
複数ある場合(~/.zshrc ~/.zshenvなど)は候補選択します。
このコマンドもシェルをよくいじる人にはキー割り当て推奨です。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
[includeme file="inc-package-relate.php" name="crux"]
