#+BLOG: rubikitch
#+POSTID: 1762
#+DATE: [2016-10-28 Fri 12:38]
#+PERMALINK: melmag257
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#257』の予告
#+TITLE: 【るびきち塾メルマガ#257】海外記事紹介＆一人旅に出ます
#+begin: org2blog-tags
# content-length: 1004

#+end:
『今回も海外記事の紹介ですっ』
「Emacs Newsはすごいいい情報源ですね」
『新しい発見が多いよ、本当』
「Sachaさんには感謝ですね」
『ああ、これからも続けていってほしいものだ』
「ところで、るびきちさんは英語が苦手だって？」
『確かに読むのは遅いけど、苦手意識はないね』
「どういうこと？」
『苦手とか難しいってのはあくまで自分が作り出した感情に過ぎない』
「つまり？」
『そういうネガティブな感情が生産性を下げるし、やらなくなってしまう』
「確かに苦手意識という言葉があるように、意識の問題なんだね」
『そーゆーこと。それに気付いたから真正面から対峙しようと思った』
「物事はやっていくうちに上達する」
『そう、成長するんだよ。やらないと成長はない』
「筋トレもやらないと筋力は衰える」
『自分に負荷をかけることが成長の秘訣！筋トレも人生も同じ』
「るびきちさん、肩周りの筋肉すごいよね」
『徹底的に鍛えたからね。英文読解もそのうち早くなるだろう。』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 2016年るびきち一人旅の目的
- 効率的に対訳を作る方法
- プロジェクトルートディレクトリを見付ける標準関数
- PHPテンプレートのためのおすすめモード
- 変数・関数リストを表示するいろいろな方法
- ありそうでなかったemacsclientの活用法
- .emacs.d集積場
- あまり知られていない標準コマンド
- 肉体的・精神的な疲れに効く即効性の高いサプリメント
などとなります。
#+END_SRC

ただいま、るびきちは旅行中ですので、
この記事は前日の予約記事から投稿しました。

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
