#+BLOG: rubikitch
#+POSTID: 1773
#+DATE: [2016-11-04 Fri 09:26]
#+PERMALINK: melmag258
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#258』の予告
#+TITLE: 【るびきち塾メルマガ#258】一人旅から得たもの＆超簡単なスマホ対応TODO管理！
#+begin: org2blog-tags
# content-length: 875

#+end:

「おーい、るびきち」
『なんや？』
「旅行どうだった？」
『そりゃめっちゃ楽しかったぜ！』
「リフレッシュって大事だよな」
『うん、それにものすごいたくさんの偶然を経験したよ』
「えっ、なになに？」
『気になる？』
「すげー気になる(笑)」
『そのヒミツは…』
「ヒミツは？」
『潜在意識さっ』
「潜在意識ってよく聞くけど、よくわからないんだよなぁ」
『一言で言うとCPUだ。すべてを司っているといっても過言じゃねぇ』
「なるほど」
『人間の力を本領発揮させるには潜在意識を良質化活性化させる必要があるっ』
「CPUをアップグレードして高性能になるってことかー！」
『そゆこと。言動は良くなるし、いいことがたくさん起こるようになるっ！』
「俺のCPU…性能低いんだよなぁ…」
『そんなこと言ったらダメっ！本当に低性能になっちまうぞ！！』
「おーこわ」
『潜在意識という名のCPUは言ったこと、思ったことを現実化するからね。悪いことは言っちゃダメ』
「高性能化の方法教えてくれっ！」
『続きはメルマガでっ♪』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 潜在意識のヒミツ
- 毎日を楽しく生きるための極意
- Emacsでもスマホでもコマンドラインでも使えるTODO管理方法
- 朝一からロケットスタートを切るための習慣
となります。
#+END_SRC


# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
