#+BLOG: rubikitch
#+POSTID: 1819
#+DATE: [2016-11-25 Fri 12:14]
#+PERMALINK: melmag261
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#261』の予告
#+TITLE: 【るびきち塾メルマガ#261】好調維持！今週も英語圏の記事を漁りますよ〜
#+begin: org2blog-tags
# content-length: 1020

#+end:
「るびきち〜、また食べすぎちまったよ」
『食べすぎちまったか…』
「どうしても食欲には勝てないんだよ」
『食欲ね。僕も3週間前まではそうだったから』
「るびきちさんもですか？」
『ああ。僕だって普通の人間だ』
「えっ？」
『君と同じ、普通の人間さ。超人でもなんでもない』
「でも、るびきちさん超人を目指しているんじゃ…」
『もちろん目指しているよ。理想だから。』
「理想、考えたことないな」
『理想は持っておけ。理想は向上心を刺激する。』
「でも、実現不可能じゃん？」
『たとえ不可能であっても一歩でも近づく、それが大事。』
「そういえば歴史上の人はみんな理想を持っていたよね」
『歴史上の人な。そうそう、偉人について書かれてる本を読むと勉強になるぜ』
「伝記とか？」
『そう、伝記とか偉人伝とかね』
「僕は凡人だけど…」
『凡人だから読むんだよ。偉人のマインドを学ぶことが目的だ』
「それなら偉人に近付ける気がするかも」
『偉人のフリをすればいい。しばらくするとそれが自然になるから。』
「カン違い乙www って言われそう」
『カン違い上等！一流の人はいい意味でカン違いして生きるものだ』
「へぇ〜」
『ってなわけで、今回ももりだくさんの内容でお届けしますっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 本気になるために必要なこと
- 僕が本当に思っていること
- ハイパフォーマンスを継続する秘密
- 誘惑に負けない方法
- 書き込み不能ファイルをrootで開き直す方法
- ディレクトリをブックマークしたときにfind-fileする方法
- find-fileは中で何をやっているのか
- 行間移動を高速化するたくさんの方法
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
