#+BLOG: rubikitch
#+POSTID: 1855
#+DATE: [2016-12-16 Fri 14:41]
#+PERMALINK: melmag264
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#264』の予告
#+TITLE: 【るびきち塾メルマガ#264】Emacs Lisp初歩の初歩！
#+begin: org2blog-tags
# content-length: 1015

#+end:
「るびきち〜、最近どうしたんだ？」
『えっ？』
「あれだけ続いてる日刊Emacsを停止するなんて！」
『あぁ、今やることが山積みなんだよ…』
「しっかり時間管理できる身体になったるびきちさんでもこなせないの？」
『ものすごい頭を使うタスクが山積み…』
「頭ってずっと働き続けられないよね」
『あぁ、今の僕はほんとに未熟。ハイパフォーマーのほんの入口に入った程度』
「でも、潜在意識が答えを導き出してくれるんでしょ？」
『ああ、そう信じてるよ。だから学び続けなきゃいけない』
「やはり学びかぁ」
『学びは脳が損傷しない限りずっと生きるからね』
「天変地異が起ころうが、戦争が起ころうが学びは生きる」
『そゆこと。学んで解決できない問題はない』
「ところで今回のメルマガは？」
『ものすごい久々にEmacs Lispについて書いた』
「難しそう…」
『いや、簡単だ。簡単なところから書いたから安心してくれ』
「四則演算とかsetqとかから？」
『そうそう。だからしばらくEmacs Lisp回は続くよ』
「ってなわけで〜」
『續きは本文でっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- Emacs Lispを学ぶ数多くのメリット
- プログラミングスキルを上げる方法
- 「Lispは宇宙である」の真意
- Emacs Lispの特性
- 「プログラミングに暗記は不要」その理由とは？
- 自信を持って学習を続ける確実な方法
- 対話的Emacs Lispシェルの使い方
- Emacs Lispの四則演算を簡単にする考え方
- コンスセルとリストの深い理解
- Lispにおける評価
- Lispにおける「ポインタ」とは？
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
