#+BLOG: rubikitch
#+POSTID: 1841
#+DATE: [2016-12-02 Fri 14:53]
#+PERMALINK: melmag262
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#262』の予告
#+TITLE: 【るびきち塾メルマガ#262】org-mode使いの小説家がいるんだって!？
#+begin: org2blog-tags
# content-length: 919

#+end:
「そういや最近のメルマガ、コラムから始まるよな」
『コラム…振り返ってみたら#x100回前後から』
「249回目からだよ」
『249回！ってことは9月初頭からだね』
「9月初頭から3ヶ月になるけど、どうだい？」
『なんか、このスタイルが気に入り始めた』
「一粒で二度おいしい的な(笑)」
『そーゆーこと(笑)ちょうど潜在意識も活性化してきたからね』
「いいなー」
『潜在意識はトレーニングで活性化できるよ、誰でも』
「トレーニングで？」
『ああ、筋トレと同じ』
「毎日やるの？しんどいなぁ…」
『眠ってる力を叩き起こすんだから大変なのは当たり前』
「そっかー。けど自分には力が眠ってると思うとワクワクしてくるよ」
『だろ？』
「るびきちさんからはEmacs以外のことも学べるし」
『僕は一生使える知識やスキルを重点的に学びたいよ』
「おお」
『なにより学んだことをアウトプットすることが大事！』
「るびきちさん、あのブログで毎日書いてたよね」
『アレな。2ヶ月かけてもう完成したからもうじき公開するよ』
「っても、ちゃっかりリンク貼ってるよね」
『うん(笑) 気付いた人いるかな？』
「いないんじゃね」
『告知してないからね。ってなわけで本文へ〜』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 子供から学べる成功への最も重要な要素
- 真の王道とは？
- org-modeを愛用する小説家の思想
- org-modeの独自の検索機能
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
