#+BLOG: rubikitch
#+POSTID: 1888
#+DATE: [2016-12-30 Fri 08:34]
#+PERMALINK: melmag266
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#266』の予告
#+TITLE: 【るびきち塾メルマガ#266】大晦日はバッククォートと振り返り
#+begin: org2blog-tags
# content-length: 915

#+end:
「今年ももう今日で最後…」
『ああ、大晦日だね』
「今年一年どうだった？」
『最高に充実した一年だった！』
「るびきちさん、今年いろいろやってきたもんね」
『まさに人生の総決算だった』
「よかったねー」
『Emacsは衰退した…か』
「あの記事、ものすごい注目されてるよね」
『Emacsはピンチを迎えたわけだ』
「大丈夫かなー」
『大丈夫だと信じてるよ。パッチ投げた人もいるし』
「けど古参のあの人が…」
『どうあれ、人間追い込まれたときにこそ信じられないほどの力を発揮するものだ』
「火事場の馬鹿力っていうもんね」
『ベストな選択をとってくれると僕は信じてる』
「Emacsは不滅！」
『ああ、不滅だよ。たとえGNU Emacsが開発停止しても、別実装が出てくるさ』
「ところで、今回のメルマガは？」
『ちょっと予定を変更して、バッククォートだ』
「リスト操作のアレね。ちょっとわかりにくいところがあって…」
『大丈夫、きっちり解説するさ』
「Emacs Lisp回は来年も続きそうね」
『しばらく続けるかな』
「ってなわけで」
『続きは本文でっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- バッククォートを使ってリストを自在操る
- avy-menuを使いこなす
- 自分を元気づける呪文をEmacsに表示させる
- Emacsの危機!？
- gitでの最古のコミットを見付ける方法
- るびきちの今年を振り返って
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
