#+BLOG: rubikitch
#+POSTID: 1866
#+DATE: [2016-12-23 Fri 14:43]
#+PERMALINK: melmag265
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
#+DESCRIPTION:
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#265』の予告
#+TITLE: 【るびきち塾メルマガ#265】Emacs Lisp入門！コマンド定義まで
#+begin: org2blog-tags
# content-length: 977

#+end:

「もう今年もあとわずか…」
『そうだねぇ、このメルマガも今年はあと2回』
「あっというまだよね」
『終わってみればね』
「るびきちさん、本当いろいろあったよね」
『ああ、寝たきりから立ち直って能力開発して〜』
「まるで高度成長期みたい」
『ほんとそれ。敗戦から復活した日本のような一年だった』
「でも今の日本は閉塞ｋ…」
『言うな！フラグ立てるんじゃねぇよｗｗ』
「るびきちさんなら」
『俺はどんどん成長すると決めたから』
「ライバルは過去の自分って言ってたよね」
『そゆこと。過去の自分に負けたらそれは後退だ』
「今年のるびきちさんは勢いあったから。」
『未来の俺は今年の俺が本当に手強いライバルになるな』
「だが超えていかないと…」
『そう。だから俺は常に本気で生きる！』
「で、今回のメルマガは？」
『Emacs Lisp回で本当に基本的なところを取り上げる』
「たとえば？」
『リスト、文字列、ローカル変数、関数・コマンド定義とか』
「一部の人には簡単すぎるかも？」
『だろーね。けど、原点回帰は大事だよ』
「そうだね。ってことで」
『続きは本文で！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- Emacs Lisp基礎の基礎
- コンスセルの基本的な扱い方
- リストの構造
- 基本的なリスト関数
- 文字列を作成する超強力な関数
- ローカル変数の基本
- Emacs Lispのローカル変数の落とし穴
- 関数を定義する意味
- 関数定義の方法
- コマンド定義の方法
- ミニバッファから情報を得る方法
となります。
#+END_SRC


# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
