#+BLOG: rubikitch
#+POSTID: 1974
#+DATE: [2017-01-27 Fri 05:47]
#+PERMALINK: melmag270
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#270』の予告
#+TITLE: 【るびきち塾メルマガ#270】Lisp流繰返し処理
#+begin: org2blog-tags
# content-length: 1061

#+end:
ども、るびきちです。

「先週から急に寒くなってきたねー」
『年明けまでは暖かかったのにねー』
「まさかの暖冬という期待があったけど」
『そりゃ冬は寒いものだ』
「それにしてもるびきちさん、前より寒さに強くなってない？」
『強くなった！』
「なんで？俺、寒さにめっちゃ弱くてさ」
『俺もだよ、以前までは』
「なにか秘密でも？」
『とにかく冬は免疫力を上げるんだ！』
「寒さや冷えは免疫力下げるっていうよね」
『そそ、俺のまわりにもいつも風邪引いてて長引いてる人いる』
「そのためには何を？」
『運動、睡眠、食事、ストレス対策』
「なんか当たり前の事を…」
『当たり前のことができないのが我々人間だよ』
「たしかになー、じゃあるびきちさんはどんなふうに？」
『野菜とタンパク質多めに摂る。プロテインも飲む量増やした。』
「肩まわりの筋肉すごいよね」
『継続すれば誰だって筋肉くらいつくよ。それとね…』
「それとね？」
『グルタミンのサプリメントを摂ること』
「グルタミンかー、免疫力上がるっていうよね」
『寝る前と寝起きに5g飲んだら寒さにめっぽう強くなった、ほんと』
「いいなー」
『本当は2度なのに8度くらいにしか感じなくなった！自分でもびっくり』
「子供みたい、うらやまー。俺も買ってみるかな…」
『さて、今回のメルマガは…』
「条件分岐の次といえば」
『ベタすぎるけど繰返し処理だ』
「基礎大事よね」
『そこでlispxmpが火を噴くぜ！』
「わお！ってことで」
『続きは本文でっ！！」

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- Emacs Lispにおける繰返し処理の基礎
- 回数指定の繰返し処理
- リストの各要素を読み取る処理
- 新しいリストを作成する際の落とし穴
- lispxmp.elの真骨頂
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
