#+BLOG: rubikitch
#+POSTID: 1952
#+DATE: [2017-01-20 Fri 04:49]
#+PERMALINK: melmag269
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#269』の予告
#+TITLE: 【るびきち塾メルマガ#269】テスト駆動開発から条件分岐を学ぶよ
#+begin: org2blog-tags
# content-length: 1136

#+end:
ども、るびきちです。

「るびきちノリノリだなww」
『ああ、絶好調さ！』
「そういや何か変わった？」
『ん〜、あっ。最近ヨガ始めたよ』
「ヨガってストレッチだろww」
『ちげーよw もっと深遠な意味がある』
「えっ」
『心と体の言い分を聞く楽しい時間』
「なるほど」
『幸福な心になるように呼吸と体からアプローチするのがヨガ』
「なるほど、人生哲学ってわけか」
『そゆこと。ちなみに今流行りの断捨離も実はヨガだよ』
「なんだって！ただいらないものを捨てまくることだと思ってた」
『断捨離は空間を快適にすることで深い呼吸をする、いわば空間のヨガ』
「たしかに人混みだと深い呼吸なんてできないね」
『だから、ヨガの観点でいろいろなものを捨てたよ』
「断捨離とか片付けにはそんな深い意味もあるんだな〜」
『ヨガというもうひとつの人生哲学が加わり成長できた』
「つーか、最近寒くてつらい…」
『ヨガは冷えにも効くよ。俺はやり始めだから毎朝30分やってる』
「30分！そんな時間なかなかとれない」
『俺は長期的視点で見てるからね。毎朝30分の投資で将来の健康レベルが上がるから』
「そう言われても…」
『ほらできない理由探してる！それがキミのいけないところだよ』
「時間どうすれば…」
『じゃあ2分からでもやってみる。そして集中する、時間管理する。』
「わかった、ぐぐってみる。で、今回のメルマガは？」
『テスト駆動開発を通していろんな条件分岐を扱うよ』
「前回、if式のあとにいきなりert扱うなんて無茶をww」
『ertは今回の布石だよ。今回はテストに守られてるのを感じてほしい』
「ってなわけで」
『続きは本文でっ！』


# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- テスト駆動開発の実践
- テストのメリット
- Emacs Lispにおける条件分岐式3つ
- 余計な条件分岐を減らすものすごい単純な関数
となります。
#+END_SRC

特に今回は実践的な内容になっています。

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
