#+BLOG: rubikitch
#+POSTID: 1995
#+DATE: [2017-02-03 Fri 09:39]
#+PERMALINK: melmag271
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#271』の予告
#+TITLE: 【るびきち塾メルマガ#271】バッファにテキストを書き出すよ
#+begin: org2blog-tags
# content-length: 1218

#+end:
ども、るびきちです。

「はやいものでもう2月…」
『そういや昨日は節分だったねー』
「豆まき♪豆まき♪」
『豆まき楽しいよねっ』
「子供と一緒にやってみたら、楽しくて〜」
『そうそう、節分の日が年ごとに前後するのって知ってる？』
「えっ、3日じゃないの？」
『2021年は2日になるんだって！』
「まじかー。知らなんだ。」
『さって、今日は地元の餅つき大会行ってくるぜ！』
「餅つき！楽しいけど腕が筋肉痛になってw」
『明らかに運動不足だね。普段から鍛えてりゃならない』
「忙しくて運動する暇なくて…」
『でも不安になったりテレビ見たりスマホいじったりする暇はあるやろ』
「ある…」
『じゃあ、その時間、1分でも体動かせばいい。』
「たとえば？」
『腕立て伏せ、バーピー、スクワット、腹筋など』
「たった1分でも変わるの？」
『毎日続ければ変わるよ、習慣化したらもっとやりたくなるから心配はいらない』
「いい習慣増やしたい」
『じゃあ、毎日1%だけ進化することを考えよう。ちょっとしたカイゼンだ』
「カイゼン！」
『1%だけならできそうだろ？』
「1%の進化を1年続けると…」
『(expt 1.01 365) を評価してみな…』
「！！！！！！！！！！！！！！！！」
『やばいだろ。1%進化の教えを学んでから俺も毎日1%ずつ速聴の速度を速くしてる』
「1%進化、僕もやってみるよ。」
『さてさて、今日のメルマガはやっとEmacs Lispらしくなるよ』
「なになに？」
『バッファに書き出す！』
「おおー。やっとバッファが出てきた。」
『しかもテストもできる』
「気になる！ってことで」
『続きは本文でっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 関数・コマンド定義の基礎(おさらい)
- エコーエリアに書き出す2つの方法
- Emacsにおける「標準出力」という概念
- 別ウィンドウにメッセージを表示させる方法
- メッセージを文字列にリダイレクトする方法
- 対話的コマンドをテストする方法
- カレントバッファに文字列を書き込む2つの方法
- Emacs Lispにおけるローカル変数の秘密
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
