#+BLOG: rubikitch
#+POSTID: 2016
#+DATE: [2017-02-10 Fri 19:37]
#+PERMALINK: melmag272
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#272』の予告
#+TITLE: 【るびきち塾メルマガ#272】超簡単！Emacs Lispでバッファを扱うよ
#+begin: org2blog-tags
# content-length: 1072

#+end:
「よぉ、るびきち！相変らず元気だな」
『よぉ！元気だぜ』
「Emacs 25.2 RC1でたなー」
『さっそく使ってるぜ』
「どう？」
『25.1.91から移行したけどまったく問題ない』
「よかったー。24.4移行時には大変な目にあったから…」
『あんなことはもうないはず。』
「なんで？」
『マイナーアップデートはバグフィクスって方針になったから』
「なら安心だね」
『25.1出たのとほぼ同時に26.1へ向けても開発されてる』
「はやっ！そういやEmacs Lisp回は去年から続いているよね」
『すげーゆっくりだけどね、やっとバッファの基礎だ』
「まだまだ続きそう」
『もうちょっとは続くかな。』
「まだ続くのかよwwww」
『広大だからな…ところで80対20の法則知ってる？』
「よく言われるあれね。Emacs Lispでいえば…」
『基礎をちゃんとやっとけば、十分ってことだよ』
「たしかに、難解な機能を掘り下げるよりも、基礎をしっかり使いこなす方が実用的だね」
『そゆこと。難しすぎたらついていけない人もでてきてしまう』
「今回はバッファの入門だよね」
『Emacs Lispを語るにおいてバッファは外せないからね』
「バッファを使いこなせればいろいろと応用できそう」
『そーゆーこと。』
「ってことで」
『続きは本文でっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- Emacsにおけるバッファの位置付け
- バッファと文字列の関係
- バッファの各機能
- 「カレントバッファ」の正しい定義
- 一連の式をキーに割り当てる方法
- カーソル移動
- 位置の取得
- カーソル位置をリセットする方法
- バッファを作成するいろいろな方法
- バッファを表示するいろいろな方法
- カレントバッファを一時的に切り替えるマクロ
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
