#+BLOG: rubikitch
#+POSTID: 2049
#+DATE: [2017-02-23 Thu 06:42]
#+PERMALINK: melmag274
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#274』の予告
#+TITLE: 【るびきち塾メルマガ#274】Emacs Lispで正規表現検索！
#+begin: org2blog-tags
# content-length: 903

#+end:
『よっ！』
「おっ、るびきち！元気になったようだな」
『ああ！立ち直りが早くなったのを感じる』
「成長してるんだな〜」
『ベストのタイミングで物事が起こってるのを感じるよ』
「いいな〜」
『なるべく長い時間いい気分でいること、これ重要』
「えっ、それだけで？」
『案外難しいよ？たとえば、嫌なことが起きたら立て続けに起こるじゃん？』
「うん」
『これ、嫌なことばかりに意識向けてるからネガティブが拡大再生産されるんだよ』
「こわっ」
『これは法則だから、逆にいい方向にも働くんだよ』
「ってことは、いいことが起これば立て続けに」
『そういうこと。喜びが拡大再生産されるんだよ！』
「いい気分でいられるにはどうすればいいか自問しよ」
『いいね！それで自分なりの答えを見付けられるはず』
「で、今日のメルマガは？」
『正規表現！』
「うげー、あれかよ…バックスラッシュ、バックスラッシュ、バックスラッシュ…」
『まぁEmacs Lispの仕様がアレだからしゃーないわ』
「まぁ…ね」
『楽をする方法も教えるから』
「ってなわけで」
『続きは本文でっ！』


# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 正規表現でできること
- Emacs正規表現、独自のメタ文字
- 正規表現の身近な活用法
- マッチデータの扱い
- occurを簡単に自作する方法
- 正規表現置換の基本
- 正規表現置換を楽にする方法
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
