#+BLOG: rubikitch
#+POSTID: 2034
#+DATE: [2017-02-17 Fri 09:39]
#+PERMALINK: melmag273
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#273』の予告
#+TITLE: 【るびきち塾メルマガ#273】検索置換 in elisp with test
#+begin: org2blog-tags
# content-length: 1101

#+end:
「よぉ、るびきち」
『よぉ』
「なにか調子悪そうだな？」
『えっ、なんでわかったww』
「なんとなくww」
『そのような振りをしてなかったけど、見破られたか。』
「だって俺だもん(どや顔)」
『ちっ、しょうがないな。べつに大したことないんだがな』
「気になるよ」
『いろいろな願いがあるんだけど、それが叶いそうなんだ』
「嬉しいことじゃん！なのになんで調子悪いんだ？」
『願い事が叶う前触れには好転反応が出ることがあるんだよ』
「好転反応っていったら、デトックスのときにでる一時的な体調不良…」
『そう、それ。それは身体のデトックスに限らず、新たなステージに立つときに起こり得る』
「一般的な好転反応は、健康になりたいという願いが叶う前触れってことか」
『そう思ってるよ。』
「で、なんで願い事が叶いそうだと思うんだい？」
『俺の周りにピンクのものが集まってくるんだよ。』
「そういや、るびきちが装着してる鈴とかピンクだな」
『集めようと思ったわけじゃないんだけど、集まるって感じ』
「女かよwww」
『出会う人もピンクの服着てたりとかさ、ピンクのものがやたら目につく』
「ピンク意識したから見つかるんじゃね？カラーバス効果ってあるじゃん」
『かもしれんけどさwwまあ、心配いらんよ』
「そこで、今回のメルマガは？」
『バッファのテストと検索置換』
「バッファは副作用あるからテストしづらいよね」
『そう。だからこれまでとは違ったテストを書く必要がある』
「なるほどね。けど検索置換ができれば処理できる幅が広がるね。」
『一気に広がるよ』
「ってなわけで」
『続きは本文でっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- バッファをテストする技法
- 文字列検索関数
- 検索結果を取り出す方法
- 検索・置換のイディオム
- 置換を楽にするライブラリ
- 置換の落とし穴
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
