#+BLOG: rubikitch
#+POSTID: 2088
#+DATE: [2017-03-24 Fri 07:42]
#+PERMALINK: melmag278
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#278』の予告
#+TITLE: 【るびきち塾メルマガ#278】バッファローカルという概念
#+begin: org2blog-tags
# content-length: 1028

#+end:
ども、るびきちです。

「よぉ、るびきち！ちょっと元気なさそうだな、お前らしくねぇ」
『わかったか（笑）さすがにごまかせんな』
「季節の変り目はどうしても身体に出てきやすいか」
『そうかも。身体が少し重い』
「で、どうした？」
『無理矢理にでも身体を動かしたよ。』
「HIIT(高強度インターバルトレーニング)か…」
『それ、ちょっとセット数多くした。そしたら元気戻ったかな』
「波はあるもんなんだな」
『落ちるところまで落ちたらあとは上がるだけって思っとる』
「いいなそれ。気楽で」
『いい意味で流れに身を任せた方が楽』
「調子悪いときどうしてる？」
『最低限の仕事をしたら瞑想とか散歩とかかな。無理はしない』
「なるほどね。無理していいことない」
『自分を見つめ直すいい機会かもって思ってるよ』
「さって、メルマガだけど前回はフックだったよね」
『そそ、フックは奥が深いね。今回はその続き』
「フック、いろいろあるよね」
『ああ、バッファローカルなフックとかも』
「バッファローカルか…たしかに変数ではあるよね」
『バッファローカル変数についても触れとくよ』
「助かる。この辺、ごっちゃになってるから」
『便利だけど知らないと混乱するからねー』
「ほんとね」
『バッファローカルフックはバッファローカル変数の一種』
「なるほど！ってことで」
『続きは本文で！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- フックの基本の復習
- バッファローカルという概念
- 2種類のバッファローカル変数とは
- バッファローカル変数の設定・参照
- バッファローカルフックとは
- バッファローカルフックの使い道
- Emacsに大きな影響を与えるフック2つ
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
