#+BLOG: rubikitch
#+POSTID: 2062
#+DATE: [2017-03-07 Tue 13:22]
#+PERMALINK: melmag276
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#276』の予告
#+TITLE: 【るびきち塾メルマガ#276】高階関数は楽しい
#+begin: org2blog-tags
# content-length: 961

#+end:

「よぉ」
『よぉ』
「暖かくなったなー」
『ほんとね。起きるの楽になったよ。』
「今年は暖冬だったのかな」
『暖冬かな、思えばストーブの前に座ることなかったな…』
「東京は雪もあまり降らなかった印象」
『そうだね。11月の初雪にはびびったけど』
「あれはびっくりだった」
『確実に春は近づいてる』
「るびきち、そういや太った？」
『ちっと太った。体脂肪が3%増えた…』
「3%か…」
『ここんとこいろいろあって感情の波が激しすぎた』
「それで食べてしまったとかね」
『そそ。今はおさまったし、これからは動きやすくなるから運動量増やすかな」
「そうだね。で、今回のメルマガは？」
『関数オブジェクト。関数引数。』
「関数引数は使いこなせると超便利！最初はびっくりしたけど」
『十分Lispらしさを感じられるはず』
「フックとかアドバイスにはもろ、関数引数が使われてるよね」
『実はEmacs Lispにおいてかなり身近な存在』
「フックといえば」
『重大な間違いが流布されてる。公式マニュアルが推奨してるからやばい』
「まぢっ!？」
『そういうところも含めて、書いていくよ』
「そんなわけで」
『続きは本文でっ！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 「関数も実はデータである」とは？
- 「関数を呼び出す関数」の使い方と具体例
- リストを引数にして関数を呼び出す方法
- 可変長引数関数を定義する方法
- lambda式とは
- 関数引数とリスト処理
- マニュアルは間違っている！フックの正しい書き方
となります。
#+END_SRC


# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
