#+BLOG: rubikitch
#+POSTID: 2070
#+DATE: [2017-03-14 Tue 14:04]
#+PERMALINK: melmag277
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#277』の予告
#+TITLE: 【るびきち塾メルマガ#277】フック入門
#+begin: org2blog-tags
# content-length: 1007

#+end:

「よぉ、るびきち！アンケート取ったんだってな？」
『取ったよ！やっぱり読者に聞くのが一番だから』
「で、どうなった？」
『フックとアドバイスが圧倒的に多かった』
「やっぱりそれかー。で、今回は？」
『前からの続きでフックを取り上げるよ。』
「そっか。普段何気なく使ってるもんな。」
『でもあまり詳しくは知らなかったりするよね？』
「ああ、ネットからのコピー＆ペーストで設定してたから」
『だから今回はちゃんと解説するよ。ネットには古い情報多いし』
「助かる。これで設定を整理できそう」
『理解できない設定は怖いからね』
「古い設定って、何のために入れたんだろうってよく思うんだ」
『とりあえず入れとけ的な？』
「そそ、だけど実際どういう役に立っているのかわからないのとかあるよね」
『Emacsユーザあるあるだね』
「で、今回はフックか」
『そう、だけど今回だけだと足りないから次回にも続きがあるけどね』
「奥が深いんだな…」
『フックは身近に使えるものから、魔界入りしそうなものまであるから…』
「げげ…」
『さすがにそこまでは触れないよ。入門の範囲超えてしまうから。』
「よかった、ってなわけで」
『続きは本文で！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- フックの概要
- フックを定義する方法
- フックに関数を登録する方法
- フックの動作の詳細
- メジャーモードに合わせてマイナーモードを設定する方法
- フック内でキーカスタマイズする方法
- ファイルを開くときに実行されるフックとは？
- 特定のファイルのみに処理を実行させる方法
- ファイルを保存する前後に実行されるフックとは？
となります。
#+END_SRC


# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
