#+BLOG: rubikitch
#+POSTID: 2090
#+DATE: [2017-04-07 Fri 10:30]
#+PERMALINK: melmag280
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#280』の予告
#+TITLE: 【るびきち塾メルマガ#280】マイナーモードを作ってしまおう
#+begin: org2blog-tags
# content-length: 1222

#+end:
『新年度2度目のメルマガですね』
「そうですね」
『あなたは新年度に慣れてきました？』
「そうだなぁ、ぼちぼちかな」
『僕はまあ、いろいろな変化があったかな』
「たとえば？」
『図書館でノマド生活を始めたよ』
「ノマドか〜、スタバというイメージあるよね。」
『近所にスタバ神社ないけどね、でも、図書館はいいよ〜』
「スタバ神社www」
『御布施を払えば1日貸し切りできる…たしかに』
「図書館はタダでいいよね」
『うん、しかも電源使えるから助かる。』
「今時のモバイルパソコンって長もちするみたいだけど…」
『僕のは2時間くらいだ＼(^o^)／』
「きついな」
『ああ、電池の持ちさえよければ、ネットブックはいいEmacs端末なんだが』
「それな」
『だから電源があるというのは大きい』
「WI-FIは？」
『使わないかな、ネットから隔離されることで集中できるし』
「ネット見られる環境だと、どうしてもネットサーフィンしてしまうよね」
『それそれ！だから、あえてオフラインな環境に身を置く』
「そういやるびきちさん、スマホもったんだよね」
『ああ、巨大スマホ兼タブレットだが。』
「じゃあテザリングできるよね」
『できるね。やったことないけど。いざというときの非常手段にしとこう』
「キャリアはなに？」
『LINEモバイル。LINE使い放題』
「えっ、るびきちさんがLINEだって？」
『ああ、宗教上の理由で使わんつもりだったが、背に腹は代えられないってやつだ』
「みんなLINEだもんな」
『時代の流れだしね』
「っと、今回のメルマガは？」
『マイナーモード』
「メジャーモードが先なんじゃ？」
『普通ならそうかもだけど、フック・アドバイスときたら…』
「マイナーモードもon/offできるしね」
『そうそう。on/offつながりで。』
「ってなわけで」
『続きは本文で♪』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- フックとアドバイスの復習
- マイナーモードの概要
- マイナーモードの内側
- キーマップの優先順位
- マイナーモードにまつわる問題
- 2種類のマイナーモード
- マイナーモードの定義方法
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
