#+BLOG: rubikitch
#+POSTID: 2099
#+DATE: [2017-04-28 Fri 14:10]
#+PERMALINK: melmag283
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#283』の予告
#+TITLE: 【るびきち塾メルマガ#283】脱・ウィンドウ構成管理
#+begin: org2blog-tags
# content-length: 955

#+end:
「よぉ〜、るびきち、最近どうだ？」
『いい感じだよ』
「図書館に通ってるんだってね？」
『ああ、以前も通ってたことあったけど、再開した』
「静かで集中できるよね」
『ほんとそれ。邪魔が入らない環境なのがいい』
「田舎だとなかなかないよね」
『きついな…でも自然の中で仕事するのはアリなんじゃ？』
「自然か！田舎だと自然環境には恵まれてるからね」
『都会疲れって言葉があるくらいだから』
「田舎はゆったりしてるしね」
『僕は東京の中でも奥の方に住んでるから田舎の良さも兼ね備えてる！』
「いいな〜」
『さすがに新宿とか渋谷とかは騒がしい(笑)』
「あーね」
『最近、いろんな人が環境の重要性を話してるけど、やっと実感できた』
「自分にあう環境は自分で作り出さなきゃいけないよね」
『そういうこと。与えられた環境がそのまま自分にあってるとは限らない』
「正解は人それぞれ」
『人生は応用問題って誰かが言ってた』
「応用問題…算数思い出した…」
『文章題とかあったね』
「あったあった」
『算数は好きだったけど、文章題はけっこう苦手だったな…』
「あるある」
『その点、計算は単純だからね。答えはひとつだし』
「文章題は人生の縮図…なのかもしれないな」
『ってなわけで、続きは本文でっ！！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- ウィンドウ構成の概要
- ウィンドウ構成とレジスタ
- ウィンドウ構成を扱う外部パッケージ
- 直前のウィンドウ構成に戻す強力な標準パッケージ
- ウィンドウ構成を超えた末…
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
