#+BLOG: rubikitch
#+POSTID: 2101
#+DATE: [2017-05-04 Thu 18:24]
#+PERMALINK: melmag284
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#284』の予告
#+TITLE: 【るびきち塾メルマガ#284】外部プログラムに触れよう
#+begin: org2blog-tags
# content-length: 1049

#+end:
『ゴールデンウィークだねぇ』
「もうすぐ終わってしまうけど」
『どう？しっかり休めた？』
「ゴールデンウィークはゴールデンウィークで大変かも」
『え？』
「仕事は休みだけどプライベートがね」
『そっかぁ』
「仕事とプライベート両立できてる人うらやま」
『わかる』
「どうすればいいのかな」
『そうねぇ、リラックス・リフレッシュが大事だと思うよ』
「あー、心身ともに休めることね」
『うん、疲れたままだと心身の状態がよくないから』
「ああ、疲れたまってる…」
『だからこそ休みをうまく使って休ませる必要ある』
「なるほどね」
『かくいう僕も人生の転機で自分に負荷かけてるんだよね』
「負荷かけないと成長はないっていうもんね」
『そういうこと、目先の快楽よりも長期的な成長を大事にしてるから』
「わあ、そんな風に考えられるのがすごいよ」
『成長すれば喜びはいくらでも手に入ることが感覚値でわかってるから』
「でも、たまには休まなきゃだね」
『そうだね。自分で言ってて改めて気付かせてもらったよ』
「土日でゴールデンウィークあけちゃうけど、しっかり休むことにするよ」
『それがいいね。』
「さて、今回のメルマガは？」
『再びEmacs Lisp回かな、シェルコマンドを扱う』
「シェルコマンド！それなら」
『Emacsだけではやりきれないことを他力でなしとげる業』
「いいなそれ！」
『Emacsの重大要素でもあるね』
「わお！ってなわけで」
『続きは本文で♪』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 外部コマンドとは？
- 外部コマンドにおけるたった1つの問題点
- Emacs向きなOS
- シェルコマンドを呼び出すコマンド
- シェルコマンドを呼び出す2つの関数
となります。
#+END_SRC


# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
