#+BLOG: rubikitch
#+POSTID: 2107
#+DATE: [2017-05-25 Thu 19:31]
#+PERMALINK: melmag287
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#287』の予告
#+TITLE: 【るびきち塾メルマガ#287】ウィンドウ構成を作ろう
#+begin: org2blog-tags
# content-length: 902

#+end:
『この前お祭りがあったぜ』
「お祭り！いいねー」
『僕はこのお祭りには毎年のように参加してる』
「楽しい？」
『楽しいよ！地元の人達たくさん集まっててさっ』
「いいねー」
『みんなで飲み食いするのもオツなものだ』
「うんうん。それはそうと、太鼓叩いた？」
『叩いたよ！思い切りね！！』
「力入れて叩いてもシケた音しかでないわw」
『あれ、コツあるんだよ。棒全体を太鼓に当てれば力なくてもいい音でる』
「ほんとか！叩くことあったらやってみる」
『スカっとするよ！大太鼓叩くの、僕の年一の楽しみだ』
「で、今日のメルマガは文字列操作だよね？」
『その予定だったけど、読者からいいお便りがきたから急遽変更だ』
「なになに？」
『ウィンドウ構成のつくり方』
「Emacsは複雑な分割状態つくれるよね」
『そう。複数のバッファを一画面で見られるようにしたいってお便り来て』
「なるほど、でも個別の関数だけだと難しそう」
『いや、実はそんなに難しくはないんだよ』
「えっ、ほんと？」
『ほんと。ちょっとしたコツあるけどね』
「まじか！ってなわけで」
『続きは本文で！！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 僕が愛用している4種類のコンピュータの使い分け
- ウィンドウ分割関数の使いこなし
- ファイルバッファを作成する方法
- ウィンドウにバッファを設定する方法
- 複雑なウィンドウ構成のつくり方
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
