#+BLOG: rubikitch
#+POSTID: 2115
#+DATE: [2017-06-23 Fri 09:29]
#+PERMALINK: melmag291
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#291』の予告
#+TITLE: 【るびきち塾メルマガ#291】るびきち新習慣
#+begin: org2blog-tags
# content-length: 1006

#+end:

『梅雨入りして2週間だけど、東京はあまり雨降ってないような』
「たしかにねー。一日雨だったのは数日くらいだったかも」
『来週からは雨ばかりになるって天気予報が…』
「まあ、そうだよね」
『順調ならばあと1ヶ月間で梅雨明だね』
「そういや、るびきち、湿度に弱いって言ってたよね」
『ああ。だけど去年までだね、今はまったく平気！』
「おおー、よかったね」
『なんか自分でも信じられないよ。体質が変わった感じ』
「1年もあれば細胞はまったく新しく生まれ変わるって聞いたことある」
『僕も聞いたことある。たしかに別人になった感じだ』
「身心相関っていうし、気持ちも変わった？」
『去年から大きく変わったね、気持ちの持ちようも健康観も』
「でも、るびきちは健康に気をつけてるんじゃ？」
『気をつけてるよ、最重要視してる！意識変えた。病気を治すよりも健康レベルを上げることにね』
「なるほど。病気のことを考えてると病気を引き寄せるって言うよね」
『そういうこと。だから、理想の健康をイメージして、それに1mmでも近付くことを目指してる』
「いいねー。そっちの方がより健康的だよね」
『そそ。若さはずっと保っておきたいからね』
「そういや今回のメルマガは？」
『コラム多め＆お便り紹介だね』
「なるほど！ってなわけで」
『続きは本文で♪』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- Debian GNU/Linuxリリース情報
- 非力なコンピュータの運用の知恵
- 目標達成のために始めたるびきち新習慣
- テンキーがない環境で数字を効率よく入力する方法
- Windows環境の理想のフォント
となります。
#+END_SRC
# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
