#+BLOG: rubikitch
#+POSTID: 2117
#+DATE: [2017-06-30 Fri 15:36]
#+PERMALINK: melmag292
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#292』の予告
#+TITLE: 【るびきち塾メルマガ#292】スマホとEmacsと…
#+begin: org2blog-tags
# content-length: 1053

#+end:

「よぉるびきち!忙しそうだな」
『やること多いよ。めっちゃ増えた(笑)』
「忙しそうで大変だな〜」
『でも充実してるよ。「忙しい」って言葉は好きじゃない。』
「なんで？」
『忙って字を分解すると「心を亡くす」と書く…』
「ああ、忙殺って言葉があるくらいだもんね」
『ネガティブな言葉は使わないように心がけてる』
「いいことだね。物事とらえようだよね」
『そう。やることが以前よりも増えたという事実は変わらない』
「事実をみて、それを忙しいと解釈するか充実してると解釈するか」
『その通り。最近エネルギー増してるから無事にこなせてるよ』
「そういやるびきち、今までは梅雨から夏にかけたら動けなくなってたんじゃ…」
『去年まではね！けど今年は大丈夫。高温多湿でも身体が耐えてくれる』
「すごーい」
『自分でもびっくりだよ。夏の間は動けなくなると見積ってたあの頃がなつかしい』
「なにかあったの？」
『使う言葉とか、環境とか、食べ物をかえた。』
「なるほど、そういうの大事だもんね」
『大事！だからこそ僕はそれらにお金、時間、エネルギーつかう』
「大事なものを大事にすることでリターン得られるもんね」
『そーゆーこと。それだけの対価がいるんだとつくづく思う。』
「なるほどー、今日のメルマガは？」
『最近はスマホと連携してるからそれについてかな』
「ちょっと変わった切り口だね」
『うん。最近はバリエーション増やそうと思ってね。』
「それとEmacsとの接し方とどう関係するか…。ってなわけで」
『続きは本文で！』

今回のメルマガであなたが得られる結果は、
- スマホやタブレットを第二のディスプレイにする方法
- メールを送信するRubyスクリプト
- メールを送信するための意外なソフトウェア
- パソコンとスマホのデータを共有する手っ取り早い方法
となります。

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
