#+BLOG: rubikitch
#+POSTID: 2109
#+DATE: [2017-06-01 Thu 19:18]
#+PERMALINK: melmag288
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#288』の予告
#+TITLE: 【るびきち塾メルマガ#288】改めて文字列処理
#+begin: org2blog-tags
# content-length: 907

#+end:
『もう6月だね〜』
「新年、新年度始まったばかりかと思ったらあっというま」
『そうだね、あっというま』
「気持ちいい五月晴れともそろそろお別れ…」
『そろそろ梅雨の季節に』
「ああ、雨ばっかりだよね」
『そういえば去年の梅雨の時期、雨降るとか言いながら降ってなかったような』
「降る降る詐欺ww」
『それwww で、秋になったら急に梅雨っぽく雨ばっかりだったような』
「思い出すね、今年はどんな感じになるだろうか」
『そういうわけで、今月は梅雨に入ってからの過ごし方のヒントも書きました』
「わおー」
『お役に立てば幸いです』
「で、本題のEmacsは？」
『改めて文字列処理だね』
「文字列処理大事だよね」
『ああ、基本中の基本だけど、まだ触れてなかったね』
「これで一通りそろったかな？」
『あ、まだだ。』
「なに？」
『リスト処理書いてないや』
「あー、ちょっと触れられてただけだよね」
『mapcarはあったけど、本格的にはまだだね』
「たしかに」
『それは次週以降にしよう。今回は文字列処理です。』
「ってなわけで」
『続きは本文で！！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- 雨の日だからこそやっておくべきこと
- org-modeで自分と対話する方法
- 文字列リテラルの復習
- 部分文字列の扱い
- 文字列を結合する2つの方法
- 正規表現の基本
- 正規表現マッチ
- 正規表現置換
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
