#+BLOG: rubikitch
#+POSTID: 2111
#+DATE: [2017-06-08 Thu 15:30]
#+PERMALINK: melmag289
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#289』の予告
#+TITLE: 【るびきち塾メルマガ#289】強力なリスト処理！
#+begin: org2blog-tags
# content-length: 920

#+end:
「よぉ！」
『よぉ！もうすぐ梅雨入りだなー』
「たしかにな、これから雨ばかりになるのか」
『僕、いつも外で作業してるから雨対策どうするか考えなきゃ』
「ノートパソコンに雨は大敵だしな」
『ああ。これまでの晴天に感謝しなきゃいけないね』
「当然、室内になってくな」
『まあ、図書館が無難かな』
「静かな場所なら図書館が本命だね」
『そうだね。』
「で、今回のメルマガは？」
『Emacs Lispのリスト処理』
「リスト処理、これまでちょくちょく触れられてきたよね」
『ほんのちょっとだけね』
「ちょっとなの？」
『氷山の一角』
「まじかー。新しい内容になるの？」
『新しいよ。でも、リスト処理をしっかり理解しておけば楽しくなる』
「楽しみ〜」
『リストとしてデータをまとめることの意味もわかるよ』
「おお！オブジェクト指向プログラミングのオブジェクトみたいにも使える？」
『まぁね。Emacs Lispではオブジェクトにまとめるよりもリストで処理することが多いね』
「Lisp自体、大昔からあるもんね」
『僕でもリストを好んで使うね、Lispでは』
「そうなのか！ってなわけで」
『続きは本文でっ！！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- るびきち突然の発熱！まさかの結末！？
- リストの構造の復習
- リスト基本関数の復習
- リストを分解するエレガントな書き方
- リストをループさせる強力な書き方
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://www.mag2.com/m/0001373131.html
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
