#+BLOG: rubikitch
#+POSTID: 2202
#+DATE: [2017-07-26 Wed 13:13]
#+PERMALINK: melmag296
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#296』の予告
#+TITLE: 【るびきち塾メルマガ#296】プロEmacser最新の思考法
#+begin: org2blog-tags
# content-length: 1442

#+end:
「るびきち、忙しそうだな」
『まぁね、最近めまぐるしい変化が訪れていてね、面白くなってきたよ』
「あっ、そうか。るびきちは忙しいという言葉を使わないんだったね」
『そーゆーこと。忙という漢字を分解してみ』
「心を亡くす…」
『そう。だからこそこんな言葉を使ってはいけない』
「忙殺という言葉があるくらいだ」
『だから言うな！言葉が人生を作ってるんだぞ』
「ごめんごめん。これから言葉には気をつけるよ」
『ある人から教わったのだが、大変になったら大きく変わるってことだって』
「その通りだね。今までとはガラッと変わる」
『だから、面白くなるんだよ。』
「そういやるびきち、ゲーム好きだよな？」
『好きだったよ。今はやらないけど、いろいろ遊んでたから少しは語れる』
「RPGって人生の縮図だと思わない？」
『それ！本当に最近腑に落ちてきたんだよ』
「ドラクエでもスライムに苦戦してるレベル1の勇者が…」
『最後はラスボスの大魔王を倒してハッピーエンド』
「人生もそれと同じじゃないかなって。自分の人生にテーマがあるとしたら」
『最後は人生の目的を達成してハッピーエンドで逝きたいものだよ』
「ドラクエ3や6の転職システム面白いよね」
『ほんとね！いろいろな仕事を経験してスキル(呪文)覚えてくとか』
「いろいろ覚えるのは大変だけどね」
『そこが面白いんだよ。いろいろな経験させてキャラが成長していくから』
「人生における人間の成長を感じられる、それがRPGの醍醐味じゃないかな」
『子供のころは何も考えずに強いキャラを作りたいという動機でやってても』
「大人になると見方が変わってくるんだよね」
『パーティーを編成するのも楽しいよね。共同プロジェクトという感じで』
「ただ暴れさせる戦士、補助呪文の僧侶、攻撃呪文の魔法使い…」
『バランスよく連携できれば一人では倒せない強敵も楽々倒せる』
「そう思えば…」
『人生はゲームなんだなと思えてきた』
「いいよね、るびきちは気楽で」
『気楽なくらいがストレスたまらなくていいかも』
「長年ゲームに没頭してたのも、そうとらえられれば必ずしも無駄時間ではないよね」
『ゲーム少年だった過去の僕に「ゲーム没頭してるのは無駄じゃないよ」と伝えられる』
「よかったね。人生には無駄な経験は一つもないんだね、本当に」
『今回のメルマガはEmacsで思考のループを解消する方法だよ』
「僕よくモヤモヤするんだよね…だから助かる！ってなわけで」
『続きは本文で！』

今回のメルマガであなたが得られる結果は、
- Emacsを使って頭の中のモヤモヤを消去する方法
- 思考力を10倍に高める方法
- 脳とコンピュータの意外な違い
- 頭の中をクリアにするための4つの魔法の質問
- 90%の日本人が陥っている最大の思考の悪癖
となります。


# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
