#+BLOG: rubikitch
#+POSTID: 2206
#+DATE: [2017-08-04 Fri 23:10]
#+PERMALINK: melmag297
#+OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil \n:t -:nil tex:nil ':nil
#+ISPAGE: nil
# (progn (erase-buffer)(find-file-hook--org2blog/wp-mode))
#+BLOG: rubikitch
#+CATEGORY: るびきち塾メルマガ
#+DESCRIPTION: るびきち塾メルマガ『Emacsの鬼るびきちのココだけの話#297』の予告
#+TITLE: 【るびきち塾メルマガ#297】すごいシンプルな全文検索ツール
#+begin: org2blog-tags
# content-length: 967

#+end:
『んー、マインド系の話はイマイチみたい…』
「たしかにね、Emacsの話あんましてないし」
『もちろん最後はEmacsにつなげるけどね』
「るびきちはテクニックよりもマインドを大事にするよね」
『そう。目的とか理由をしっかり決めること大事と思ってる』
「中にはテクニックを求めてる人も…」
『いるねえ。ただ、はっきりとした目的がないと意味がなくなる』
「なるほど、目的ね」
『それは長年の経験から悟ってきている』
「るびきちにとってEmacsとは？」
『人生！というか思考を現実化させるための強力なツールだね』
「ああ、コードも文章も思考から始まるもんね」
『そーゆーこと。思考を掘り下げる場合にもEmacsを使うよ、前回触れたみたいに』
「あまりそういう使い方する人いないよね」
『かもねー。わからんけど。どうあれEmacsは習熟度が上がればなんでもできるから』
「なじんでいく感覚？」
『そんな感じね。今回は久々に検索がテーマだよ』
「おお」
『grepで全文検索。ちょっと思い付いたから』
「grepなら速度も問題ないね！ってなわけで」
『続きは本文で！』

# (wop)
#+BEGIN_SRC org
今回のメルマガであなたが得られる結果は、
- M-x grepが受け付ける全文検索ツールのありかた
- メモの格納方法の比較
- grepで複数のキーワードを全文検索する方法
- 超音速grepツール！
- Emacs内でのみ使われるスクリプトを置く場所
- シンプル全文検索ツールの仕様・ソースコード
- anything-grep.elと全文検索を連携させる方法
となります。
#+END_SRC

# footer
豪華な入塾特典付きで、初月無料月々527円のるびきち塾。
Emacsについて、人生の質を上げる方法について
メルマガでも個別メールでも懇切丁寧に指導します。
絶対に損はさせませんので、ぜひとも登録してください。
http://rubikitch.com/juku/
1週間あたり缶ジュース1本分の投資で、僕があなたのメンターになります。

# (progn (forward-line 1)(shell-command "screenshot-time.rb org_template" t))
